-- Inline-authored deep rationales + distractor rationales — batch 001
-- 9 NCLEX questions covering OB hemorrhage, delegation, endocrine, anticoagulants,
-- chain-of-command, and hypoglycemia rescue. Tuned for the exam-prep premium lane.

UPDATE questions SET
  deep_rationale = 'A respiratory rate of 8 with somnolence is opioid-induced respiratory depression — giving more morphine IV push would deepen CNS and brainstem suppression and risk apnea. The nurse''s legal and ethical duty when an order is unsafe is to question and clarify with the prescriber FIRST. If the order stands and the nurse still believes it is unsafe, escalate up the chain of command (charge nurse → nursing supervisor → medical director) and document the conversation. The Nurse Practice Act protects nurses who refuse unsafe orders; it does not protect "I was just following orders." The decisive clinical anchor here is RR<12 plus difficulty arousing = sedation scale 4+, which calls for naloxone consideration, not more opioid. Pearl: when a vital sign and an order contradict, the vital sign wins until the discrepancy is resolved by the prescriber.',
  distractor_rationales = '{"b":"Administering a written order that is clearly unsafe does not transfer liability — the nurse who pushes the medication owns the harm under the Nurse Practice Act.","c":"Ignoring an order without escalation leaves the client at risk and creates a documentation gap that will surface in any incident review. The duty is to escalate, not to silently refuse.","d":"Delegating the unsafe order to another RN does not make the order safe and exposes the second nurse to the same liability. Chain of command, not lateral handoff, is the appropriate path."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1903-n024';

UPDATE questions SET
  deep_rationale = 'Umbilical cord prolapse is a true obstetric emergency: the cord slips below the presenting part after rupture of membranes, gets compressed against the cervix or pelvis, and fetal oxygenation collapses within minutes. The hallmark is sudden, profound, sustained fetal bradycardia immediately after ROM, often with a visible or palpable cord at the introitus. The first nursing move is mechanical decompression — gloved hand inside the vagina to lift the presenting part off the cord, AND place the mother in knee-chest or steep Trendelenburg to use gravity. Call for help, prepare for emergency cesarean, give oxygen 10 L by mask, and DO NOT attempt to reduce (push back) the cord. Pearl: any deceleration immediately after ROM is cord prolapse until proven otherwise; the bedside answer is always position and lift, not assess and wait.',
  distractor_rationales = '{"b":"Variable or transient decelerations may follow ROM but a sustained bradycardia with a palpable cord is mechanical compression, not a self-resolving tracing.","c":"Placenta previa presents with painless bright-red bleeding without ROM-triggered bradycardia; it is not a cord-emergency map.","d":"Fetal sleep cycles produce decreased variability with a normal baseline, not the abrupt deep bradycardia seen with cord compression."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1021-n007';

UPDATE questions SET
  deep_rationale = 'Delegation to UAP is governed by the five rights — right task, right circumstance, right person, right direction, right supervision — and the NCSBN principle that the RN may delegate any task that does NOT require nursing judgment, assessment, evaluation, or teaching. Routine vitals on a stable chronic-HF client (A), ambulation per a written plan on a cleared post-op (C), and I&O measurement on a stable client (E) are all within the UAP scope: they are observable, measurable, and protocol-driven. Teaching incentive spirometer use (B) requires the RN because evaluating return demonstration and clinical understanding are nursing assessments. Initial assessment of new chest pain (D) is the highest-acuity exclusion — pain that has not yet been characterized requires the RN to determine if it is cardiac, pleuritic, or musculoskeletal. Pearl: if the task starts with "assess," "teach," "evaluate," or "interpret" — it stays with the RN.',
  distractor_rationales = '{"b":"Teaching is an RN-only responsibility because it requires real-time evaluation of comprehension and return demonstration, both clinical judgments outside the UAP scope.","d":"Initial assessment of a new, uncharacterized complaint requires RN judgment to triage cardiac vs. non-cardiac pain. UAP can recheck vitals only after the RN has assessed."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1901-n016';

UPDATE questions SET
  deep_rationale = 'Ruptured ectopic pregnancy is the leading cause of first-trimester maternal death. The implantation site (usually fallopian tube) cannot sustain a growing pregnancy, and rupture causes brisk intraperitoneal hemorrhage. The diagnostic cluster is unilateral pelvic pain + positive pregnancy test + hemodynamic instability (tachycardia, hypotension, syncope) + referred shoulder pain from diaphragmatic irritation by free blood (Kehr sign). The first nursing move is to anticipate hemorrhagic shock: two large-bore IVs, type and crossmatch, NPO for OR, continuous vital monitoring, and immediate provider notification. Definitive treatment is surgical (laparoscopic salpingectomy or methotrexate if still unruptured and stable). Pearl: any first-trimester client with abdominal pain and a positive pregnancy test gets ruled OUT for ectopic before any other diagnosis is entertained — vaginal bleeding may be minimal because most of the blood is inside the abdomen.',
  distractor_rationales = '{"b":"Implantation discomfort is mild, midline, and brief — it does not produce shoulder pain or hemodynamic instability and never warrants delayed evaluation in a positive-pregnancy client.","c":"Placenta previa is a third-trimester problem (painless bright-red bleeding) and requires a previously visualized uterine pregnancy, not first-trimester triage.","d":"Hyperemesis presents with persistent vomiting and weight loss, not unilateral pain and shoulder referral; it does not explain a hemodynamic shock map."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1025-n012';

UPDATE questions SET
  deep_rationale = 'Severe hypoglycemia (BG <54) with altered mental status and an unprotected airway is a true emergency — oral carbohydrate is contraindicated because the client cannot protect their airway and will aspirate. Glucagon 1 mg IM is the fastest nurse-administered rescue when IV access is uncertain or absent: it stimulates hepatic glycogenolysis and raises BG within 10-15 minutes. Once consciousness returns, follow with a complex carbohydrate + protein snack to prevent recurrence (glucagon depletes glycogen stores so a second drop is common within 60-90 minutes). IV D50 (25 g of D50W push) is also correct WHEN IV access exists and is patent — many institutional protocols list it as first-line for this exact scenario, but it requires an order and confirmed IV. D5W at 125 mL/hr delivers only ~6 g/hr — far too slow for symptomatic neuroglycopenia. Pearl: if the client cannot swallow safely AND IV access is uncertain → glucagon IM; if IV is patent → D50 push.',
  distractor_rationales = '{"a":"Oral carbohydrate is contraindicated when swallowing is unsafe — aspiration risk outweighs glycemic benefit. The Joint Commission flags this as a sentinel-event pathway.","c":"D5W at 125 mL/hr provides ~6 g dextrose per hour, far below the bolus needed to correct neuroglycopenia. It is a maintenance, not a rescue, fluid.","d":"Rechecking glucose without treating buys time the client does not have — neuroglycopenia can progress to seizure and coma within minutes. Treat first, recheck after."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb001-n002';

UPDATE questions SET
  deep_rationale = 'HELLP syndrome (Hemolysis, Elevated Liver enzymes, Low Platelets) is a severe variant of preeclampsia that can occur even with only mildly elevated blood pressure. The pathophysiology is endothelial dysfunction → microangiopathic hemolytic anemia + hepatic ischemia (causing RUQ or epigastric pain) + platelet consumption. Classic triad: RUQ pain, AST/ALT elevation, platelets <100k. Management is delivery as the only definitive treatment, with magnesium sulfate for seizure prophylaxis, antihypertensives (labetalol or hydralazine) for SBP >160 or DBP >110, and platelet transfusion if <20k or actively bleeding. The biggest pitfall is mistaking the RUQ pain for cholecystitis or reflux and missing the obstetric emergency. Pearl: any pregnant client >20 weeks with epigastric or RUQ pain gets a CBC and LFTs before any GI workup — HELLP can rupture the liver capsule and kill within hours of presentation.',
  distractor_rationales = '{"b":"Reflux in pregnancy is positional, postprandial, and not accompanied by lab derangement or hypertension — it does not explain falling platelets or elevated AST.","c":"Gallbladder disease can mimic the pain location but does not produce hemolysis, thrombocytopenia, or the hypertensive map of HELLP.","d":"Musculoskeletal pain from uterine growth is mechanical, not associated with lab abnormalities, and does not have a worsening BP signature."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1341-n011';

UPDATE questions SET
  deep_rationale = 'Insulin-induced hypoglycemia produces neuroglycopenia (CNS glucose deprivation): diaphoresis, tremor, confusion, tachycardia from sympathetic surge. Untreated, it progresses to seizure, coma, and irreversible neuronal injury within minutes — glucose <40 mg/dL is associated with measurable cognitive damage on repeated exposure. The bedside rule of 15: 15 g fast-acting carbohydrate (4 oz juice, glucose tabs) → recheck in 15 minutes → repeat if still <70 mg/dL. If the client cannot swallow safely, give glucagon 1 mg IM or D50 25 g IV push. Once corrected, follow with a complex carb + protein to prevent rebound, because short-acting insulin can outlast a glucose-tab fix. The mistake to avoid: waiting for an order when the client is symptomatic — nursing protocols allow hypoglycemia rescue under standing orders precisely because seconds matter. Pearl: a confused diabetic just dosed with insulin is hypoglycemic until a fingerstick proves otherwise.',
  distractor_rationales = '{"b":"Delaying glucose correction for an order conversation when the client is actively neuroglycopenic risks seizure — standing hypoglycemia protocols exist specifically to remove this delay.","c":"Restricting carbohydrate during active hypoglycemia is harmful — there is no rebound risk in the acute treatment phase; the issue is preventing progression to coma.","d":"Exercise increases glucose uptake and would deepen hypoglycemia. It is contraindicated in the symptomatic phase."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1901-n009';

UPDATE questions SET
  deep_rationale = 'Uterine atony causes 75-80% of primary postpartum hemorrhage (>1000 mL within 24 hours of birth). The pathophysiology: after placental separation, contracted myometrial fibers compress spiral arteries — when contraction fails, those arteries bleed unchecked. The classic finding is a boggy, soft, or displaced uterine fundus above the umbilicus, often pushed up and to the right by a full bladder. First-line nursing actions in sequence: (1) firm fundal massage with the lower hand supporting the uterus, (2) empty the bladder (full bladder displaces the uterus and prevents contraction), (3) IV access and oxytocin per protocol, (4) escalate for second-line uterotonics (methylergonovine, carboprost — contraindicated in HTN and asthma respectively), (5) prepare for surgical intervention (B-Lynch suture, balloon tamponade, hysterectomy). Pearl: a soft fundus with heavy lochia is atony until proven otherwise — massage and empty the bladder before reaching for any other intervention.',
  distractor_rationales = '{"b":"Normal lochia is dark red, scant-to-moderate, and accompanied by a firm midline fundus — heavy bleeding plus a boggy fundus is never normal.","c":"Placenta previa is an antepartum diagnosis with painless bleeding before delivery; it does not explain postpartum atony.","d":"Fatigue does not produce a boggy fundus or active hemorrhage — perfusion concern requires a uterine source, not a generalized state."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1340-n012';

UPDATE questions SET
  deep_rationale = 'Warfarin is a vitamin K antagonist that inhibits clotting factors II, VII, IX, X — the therapeutic window is narrow (INR 2-3 for most indications, 2.5-3.5 for mechanical mitral valves) and major bleeding is the dominant risk. The single highest-yield teaching point: recognize occult bleeding early. Black, tarry stools (melena) indicate upper GI bleeding from gastric or duodenal source — at warfarin therapeutic levels, a small GI lesion can produce life-threatening hemorrhage. Other report-immediately findings: hematuria, bright red blood per rectum, unexplained bruising, severe headache (intracranial bleed), or fall with head strike. Vitamin K antagonism reverses with oral or IV vitamin K (slow, hours) or 4-factor PCC (fast, minutes) for life-threatening bleeding. Pearl: never double a missed warfarin dose — INR is dose-cumulative and doubling overshoots into bleeding range; skip the missed dose and resume the next scheduled one if >12 hours late.',
  distractor_rationales = '{"b":"Gum bleeding from brushing is a warning sign of over-anticoagulation, not an expected finding. It should prompt the client to report and have INR checked, not normalize the symptom.","c":"Skipping INR checks defeats the purpose of titrated therapy — INR drifts with diet, antibiotics, and any new medication, so monitoring is non-negotiable.","d":"Doubling a missed dose pushes INR past therapeutic range into bleeding territory — never double an anticoagulant dose."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1172-n024';
