-- Inline-authored deep rationales — batch 002
-- 15 high-stakes NCLEX emergencies: airway, anticoagulation, endocrine,
-- OB, spinal, transfusion, toxicology, anesthesia.

UPDATE questions SET
  deep_rationale = 'Active pulmonary TB spreads via droplet nuclei small enough to stay suspended in air for hours, so it mandates AIRBORNE precautions: a fit-tested N95 respirator (or PAPR), a negative-pressure isolation room with the door closed, and the client masked during any transport. Because TB care often involves direct contact with respiratory secretions, add a gown and gloves. A surgical mask does NOT filter droplet nuclei — its weave is too coarse and it does not seal to the face. The decisive distinction tested here: airborne (TB, measles, varicella) = N95; droplet (influenza, pertussis, meningococcus) = surgical mask. Pearl: "My Chicken Hez TB" — Measles, Chickenpox, Herpes zoster (disseminated), TB are the airborne four. Get the respirator on BEFORE entering the room, and confirm the negative-pressure indicator is reading correctly.',
  distractor_rationales = '{"a":"A surgical mask cannot filter droplet nuclei and does not seal to the face — it is appropriate for droplet precautions, not airborne TB.","c":"An N95 alone omits the gown and gloves needed when direct contact with respiratory secretions is anticipated during TB care.","d":"A face shield plus surgical mask addresses splash/droplet exposure but still lacks the N95 seal required to filter airborne TB nuclei."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb001-n005';

UPDATE questions SET
  deep_rationale = 'A therapeutic aPTT on IV heparin is roughly 1.5-2.5x control (about 60-80 seconds in most labs). An aPTT of 149 is dangerously supratherapeutic — the client is at high risk for major hemorrhage (intracranial, GI, retroperitoneal). The priority is to STOP the infusion immediately to halt further anticoagulant delivery, then notify the provider and follow the heparin protocol (which typically holds the drip, rechecks aPTT in ~1 hour, and resumes at a reduced rate). For life-threatening heparin bleeding, the antidote is protamine sulfate — NOT vitamin K (that reverses warfarin). The decisive reasoning: when a value is critically high on a continuous anticoagulant, stopping the source comes before any dose adjustment or notification. Pearl: heparin monitors with aPTT and reverses with protamine; warfarin monitors with INR and reverses with vitamin K. Mixing these up is a classic NCLEX trap.',
  distractor_rationales = '{"a":"Increasing the rate when the aPTT is already 149 would compound an overdose and push the client into life-threatening hemorrhage.","c":"Vitamin K reverses warfarin, not heparin. The heparin antidote is protamine sulfate, and reversal is reserved for active bleeding.","d":"An aPTT of 149 is critically supratherapeutic, not expected — documenting without acting leaves the client at active bleeding risk."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb003-n001';

UPDATE questions SET
  deep_rationale = 'Blood glucose 47 with diaphoresis and confusion is symptomatic hypoglycemia with neuroglycopenia — and because oral intake is unsafe (aspiration risk from altered consciousness), the airway protects against giving juice. The parenteral rescue depends on access: with a patent IV, push D50 (25 g of 50% dextrose); without IV access, give glucagon 1 mg IM/SubQ, which triggers hepatic glycogenolysis and raises glucose in 10-15 minutes. Recheck glucose in 15 minutes and, once the client can swallow, follow with a complex carbohydrate + protein to prevent rebound (glucagon depletes glycogen stores, so a second drop is common). Untreated, glucose <40 risks seizure, coma, and permanent neuronal injury. Pearl: the swallow-safety check is the fork in the road — alert and able to swallow gets 15 g oral carbs (rule of 15); altered or NPO gets parenteral rescue.',
  distractor_rationales = '{"a":"Oral juice is contraindicated when the client cannot swallow safely — aspiration risk outweighs the glycemic benefit.","c":"Waiting 15 minutes without treating active neuroglycopenia risks progression to seizure and coma; treat first, recheck after.","d":"Insulin lowers glucose further and would deepen a life-threatening hypoglycemic emergency — never give insulin for hypoglycemia."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb003-n002';

UPDATE questions SET
  deep_rationale = 'The ABG defines the emergency: pH 7.28 + PaCO2 58 = acute respiratory acidosis from alveolar hypoventilation, and PaO2 54 on 4 L confirms refractory hypoxemia. With RR 32 and accessory-muscle use, this client is in acute hypercapnic respiratory failure and fatiguing fast. Non-invasive positive-pressure ventilation (BiPAP) is the priority intervention because it does two things oxygen alone cannot: the IPAP (inspiratory pressure) augments tidal volume to blow off CO2 and correct the acidosis, while EPAP improves oxygenation by recruiting alveoli. Early NIPPV in this picture (classically a COPD exacerbation) can avert intubation. Simply increasing FiO2 raises PaO2 but does nothing for the rising CO2 — and in CO2 retainers, over-oxygenation can blunt the hypoxic drive and worsen hypercapnia. Pearl: when both pH and PaCO2 are deranged with respiratory fatigue, the answer addresses VENTILATION (BiPAP), not just oxygenation.',
  distractor_rationales = '{"a":"Increasing nasal cannula flow raises FiO2 slightly but does nothing to remove CO2 or correct the acidosis driving the failure.","b":"A non-rebreather floods oxygen but provides no ventilatory support; it cannot lower the PaCO2 of 58 or reverse the acidosis.","d":"A chest X-ray is diagnostic, not therapeutic — obtaining imaging while the client fatigues delays the ventilatory support that prevents intubation."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb001-n004';

UPDATE questions SET
  deep_rationale = 'Delegation to UAP follows the five rights and the bright-line rule: the RN may delegate only tasks that are routine, predictable, and free of nursing judgment, assessment, evaluation, or teaching. Obtaining a routine blood pressure on a STABLE client fits — it is a measurable, protocol-driven task within the UAP scope. The three excluded options each require RN licensure: assessing a surgical incision for infection is an assessment (interpreting findings), teaching foot care requires evaluating comprehension, and interpreting telemetry is clinical analysis. The trap is that UAPs can physically perform many of these motions (apply a cuff, look at a strip) — but the RN owns any task whose VALUE lies in clinical interpretation. Pearl: if the verb is assess, teach, evaluate, interpret, or plan, it stays with the RN; if it is measure, collect, transport, or assist-per-plan on a stable client, it can be delegated.',
  distractor_rationales = '{"a":"Assessing an incision for infection requires interpreting clinical findings — an RN assessment that cannot be delegated.","c":"Teaching requires real-time evaluation of client understanding and return demonstration, both RN responsibilities.","d":"Interpreting telemetry rhythm strips is clinical analysis requiring RN licensure, not a delegable measurement task."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb001-n003';

UPDATE questions SET
  deep_rationale = 'Autonomic dysreflexia is a life-threatening emergency in clients with spinal cord injury at or above T6. The pathophysiology: a noxious stimulus below the injury level (most often a distended bladder from a kinked/blocked catheter, or fecal impaction) triggers massive sympathetic discharge. Below the lesion there is intense vasoconstriction and severe hypertension; above the lesion the body tries to compensate with vasodilation, producing the classic pounding headache, flushing/sweating above the injury, and reflex bradycardia. Untreated, the hypertensive surge can cause stroke or seizure. First actions: sit the client UPRIGHT (orthostatic drop lowers BP), then find and remove the trigger — check the catheter for kinks/blockage first, since bladder distention is the most common cause. Pearl: the immediate moves are "sit them up and unblock the bladder" before any antihypertensive — relieving the trigger often resolves the crisis on its own.',
  distractor_rationales = '{"b":"Chronic hypertension does not produce abrupt headache, sweating above the lesion, and a clear bladder trigger in a high SCI client.","c":"Orthostatic hypotension causes LOW blood pressure on position change — the opposite of the hypertensive surge seen here.","d":"A migraine has no autonomic bladder trigger and does not explain the dangerous blood-pressure spike of dysreflexia."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb973-n011';

UPDATE questions SET
  deep_rationale = 'Chills, low-back pain, and chest tightness within the first 15 minutes of a transfusion are the signature of an acute hemolytic transfusion reaction — usually ABO incompatibility, where recipient antibodies destroy donor RBCs, releasing free hemoglobin that can cause flank/back pain, DIC, and acute kidney injury. The first and non-negotiable action is to STOP the blood immediately and disconnect the tubing at the hub (do not just clamp — you want no more incompatible cells entering). Then keep the line open with normal saline via NEW tubing, take vital signs, notify the provider and blood bank, and send the blood bag plus a fresh blood/urine sample for workup. Saline is the only fluid compatible with blood; dextrose lyses cells and LR contains calcium that clots the line. Pearl: stop-saline-notify-send is the fixed sequence, and you stop FIRST because every additional mL of incompatible blood worsens the hemolysis.',
  distractor_rationales = '{"b":"Warming discomfort does not produce back pain and chest tightness — these are hemolytic reaction signs, not a comfort issue.","c":"Attributing the symptoms to anxiety ignores a time-locked transfusion reaction and risks fatal continued hemolysis.","d":"Charting while the blood continues delivers more incompatible cells — the blood must be stopped before any documentation."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1344-n015';

UPDATE questions SET
  deep_rationale = 'Soot in the nares/mouth, singed nasal hairs, a hoarse voice, and stridor after a burn — especially one sustained in an enclosed space — signal inhalation injury with impending airway obstruction. Heat and chemical irritants cause progressive mucosal edema of the upper airway; stridor means the lumen is already narrowing and total occlusion can follow within minutes to hours. The priority is early airway protection: anticipate and prepare for endotracheal intubation BEFORE the airway swells shut, because once edema is advanced, intubation becomes extremely difficult or impossible (and a surgical airway may be needed). Give humidified high-flow oxygen, keep the head of bed elevated, and escalate immediately. Pearl: in inhalation injury you intubate early on the trajectory, not after collapse — "if you are thinking about the airway, secure it now," because waiting converts an elective intubation into a crash airway.',
  distractor_rationales = '{"b":"Stridor and hoarseness signal active airway narrowing, not benign irritation — observing while doing wound care risks losing the airway.","c":"Pain-related hyperventilation does not cause soot, hoarseness, or stridor; this is a mechanical airway threat.","d":"Hydration does not reverse progressive mucosal edema from inhalation injury — the airway must be secured early."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb975-n010';

UPDATE questions SET
  deep_rationale = 'DKA is a triad of hyperglycemia, ketoacidosis, and profound volume depletion from osmotic diuresis — clients can be 6-10 L down. Hypotension, tachycardia, and Kussmaul respirations mark perfusion failure, so the FIRST priority is aggressive isotonic fluid resuscitation (0.9% normal saline), often 1-1.5 L in the first hour, BEFORE the insulin infusion is fully relied upon. Fluids alone lower glucose by dilution and restored renal perfusion, and they prevent the circulatory collapse that kills. The sequencing trap: insulin is essential but is started carefully and never before checking potassium — insulin drives K+ intracellularly and can precipitate fatal hypokalemia in a total-body-K-depleted patient. So the order is fluids first, verify/replace potassium, then insulin drip; add dextrose once glucose falls to ~200 to avoid hypoglycemia while ketones clear. Pearl: in DKA, "fluids before insulin, and never push insulin until you know the K+."',
  distractor_rationales = '{"b":"Long-acting insulin does not address the shock and acidosis, and giving insulin before fluids/potassium risks fatal hypokalemia and collapse.","c":"This is not simple dehydration — the acidosis and hypotension require IV isotonic resuscitation, and a high serum K+ in DKA masks total-body depletion.","d":"Hypotension and Kussmaul breathing make this an active emergency, not a stable issue that can wait for repeat labs."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1021-n010';

UPDATE questions SET
  deep_rationale = 'The classic intussusception triad in an infant 3 months-3 years: sudden episodic colicky pain (the infant draws knees to chest and screams, then settles between episodes), vomiting, and "currant-jelly" stools — a mix of blood and mucus from bowel ischemia. The mechanism is telescoping of one bowel segment into the adjacent distal segment, which compresses the mesenteric vessels, causing venous congestion, mucosal sloughing (the currant-jelly), and progressing to bowel necrosis and perforation if not relieved. This is a surgical/radiologic emergency: keep the infant NPO, establish IV access, and prepare for an air or hydrostatic (contrast) enema, which is both diagnostic and frequently therapeutic (reduces the telescoped segment); surgery follows if reduction fails or perforation is suspected. Pearl: currant-jelly stool + intermittent knees-to-chest pain in a toddler = intussusception until proven otherwise — protect perfusion and escalate, do not wait it out.',
  distractor_rationales = '{"b":"Teething causes drooling and gum discomfort, not currant-jelly stools or episodic knees-to-chest pain with vomiting.","c":"A viral illness does not produce blood-and-mucus stools and the bowel-obstruction pain pattern of intussusception.","d":"Transient feeding intolerance lacks the ischemic currant-jelly stool and obstructive picture that mark a perfusion emergency."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1013-n009';

UPDATE questions SET
  deep_rationale = 'Recurrent late decelerations — a gradual fall in fetal heart rate that begins after the contraction peak and returns to baseline after the contraction ends — signal uteroplacental insufficiency: the placenta cannot deliver enough oxygen during contractions, producing fetal hypoxemia. When they recur, especially with tachysystole from an oxytocin drip, the fetus is at risk for acidosis. Intrauterine resuscitation is the priority bundle: STOP/decrease the oxytocin (remove the stressor), reposition the mother to left lateral (relieves aortocaval compression and improves placental flow), give an IV fluid bolus (boosts maternal preload and placental perfusion), and apply 10 L oxygen by non-rebreather; notify the provider and prepare for possible expedited delivery if the pattern persists. Pearl: lates = placenta problem; the mnemonic for the rescue bundle is "turn off the pit, turn the mom, turn up the fluids and O2." Variables, by contrast, are cord compression and call for repositioning first.',
  distractor_rationales = '{"b":"Recurrent late decelerations are non-reassuring, not benign — they require active intrauterine resuscitation, not observation alone.","c":"Late decelerations reflect uteroplacental compromise, not fetal sleep; sleep affects variability, not the deceleration timing.","d":"This is a fetal oxygenation problem, not maternal discomfort — ignoring it risks fetal acidosis."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1341-n012';

UPDATE questions SET
  deep_rationale = 'Lithium has a razor-thin therapeutic window (0.6-1.2 mEq/L; toxicity climbs above 1.5) and is handled by the kidney exactly like sodium — the two compete for reabsorption in the proximal tubule. This is the key teaching point: anything that drops sodium or volume makes the kidney reabsorb MORE lithium, spiking levels into toxicity. So the correct understanding is to keep sodium and fluid intake CONSISTENT (about 2-3 L/day) and to report diarrhea, vomiting, or heavy sweating promptly, because each causes volume/sodium loss that concentrates lithium. NSAIDs (ibuprofen), thiazide diuretics, and ACE inhibitors also raise lithium levels and should be avoided unless monitored. Early toxicity: nausea, fine tremor, polyuria; advancing toxicity: coarse tremor, ataxia, confusion, seizures. Pearl: "salt and water steady" — a low-sodium diet or dehydration is the fastest route to lithium toxicity, the opposite of what many clients assume.',
  distractor_rationales = '{"a":"Limiting salt is dangerous on lithium — low sodium makes the kidney reabsorb more lithium and drives toxicity.","c":"Lithium must be taken consistently; stopping when mood improves risks relapse and destabilizes therapeutic levels.","d":"Ibuprofen and other NSAIDs reduce renal lithium clearance and raise levels into the toxic range — they should be avoided."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb889-n001';

UPDATE questions SET
  deep_rationale = 'Magnesium sulfate (given for seizure prophylaxis in preeclampsia and as a tocolytic) is a CNS and neuromuscular depressant with a narrow safe range (therapeutic ~4-7 mEq/L). Toxicity progresses predictably as the level climbs: loss of deep tendon reflexes (the earliest reliable warning, ~8-10), then respiratory depression (~10-12), then cardiac arrest (>15). This client shows depressed respirations, absent reflexes, and low urine output — the last is critical because magnesium is renally cleared, so oliguria causes accumulation. The emergency response: STOP the magnesium infusion immediately, support the airway/ventilation, and give the antidote calcium gluconate IV (1 g), which directly antagonizes magnesium at the neuromuscular junction. Monitor reflexes, respirations (keep RR >12), and urine output (>30 mL/hr) on any mag drip. Pearl: check reflexes and respirations before and during the infusion — absent reflexes is the signal to stop the mag and reach for calcium gluconate.',
  distractor_rationales = '{"b":"Absent reflexes and respiratory depression are toxicity signs, not normal fatigue — this requires stopping the infusion now.","c":"Anxiety does not abolish deep tendon reflexes or depress respirations; this is a medication-accumulation emergency.","d":"Magnesium toxicity is progressive and lethal — it cannot wait for routine reassessment; the antidote is needed promptly."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1341-n013';

UPDATE questions SET
  deep_rationale = 'Malignant hyperthermia is a genetic, life-threatening reaction to volatile anesthetics (halothane, sevoflurane, isoflurane) and the depolarizing paralytic succinylcholine. A mutated ryanodine receptor causes uncontrolled calcium release from skeletal-muscle sarcoplasmic reticulum, driving a hypermetabolic crisis. The EARLIEST and most specific sign is a sharp rise in end-tidal CO2 (from the metabolic explosion) together with masseter/generalized muscle rigidity — these precede the hallmark soaring temperature, which is actually a late finding. Management is immediate and bundled: discontinue the triggering agent, give dantrolene (the antidote; it blocks sarcoplasmic calcium release) at 2.5 mg/kg IV and repeat as needed, hyperventilate with 100% oxygen, and aggressively cool the client (cooled IV fluids, surface cooling) while treating hyperkalemia and acidosis. Pearl: do not wait for fever — rising end-tidal CO2 plus rigidity after anesthesia IS malignant hyperthermia; reach for dantrolene immediately.',
  distractor_rationales = '{"b":"Postoperative shivering does not raise end-tidal CO2 or cause muscle rigidity — warming blankets would dangerously delay dantrolene.","c":"Emergence anxiety does not produce the hypermetabolic rigidity-and-rising-CO2 picture of malignant hyperthermia.","d":"Dehydration is not an anesthetic emergency and does not explain rigidity with climbing end-tidal CO2."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1341-n014';

UPDATE questions SET
  deep_rationale = 'The triad of slow respirations (RR <12), depressed level of consciousness/poor arousal, and pinpoint (miotic) pupils after an opioid dose is opioid-induced respiratory depression — the dose-limiting and lethal toxicity of opioids, which suppress the brainstem respiratory drive. The priority is ventilation: stimulate the client, open the airway, support breathing with bag-mask and supplemental oxygen, and prepare naloxone (Narcan) 0.04-0.4 mg IV titrated to restore adequate respirations without fully reversing analgesia or precipitating acute withdrawal. Because naloxone has a shorter half-life than most opioids, the client must be monitored for re-sedation and may need repeat dosing. Hold further opioids and recalculate the regimen. Pearl: pinpoint pupils + low RR + sedation = opioid toxicity; treat the breathing first (oxygen and ventilation), then give titrated naloxone — the goal is a breathing patient, not a wide-awake one in withdrawal.',
  distractor_rationales = '{"b":"Normal sleep does not depress the respiratory rate to dangerous levels or cause pinpoint pupils — this is oversedation, not rest.","c":"Pinpoint pupils with a low respiratory rate is a medication emergency, not benign surgical fatigue.","d":"Slow breathing here reflects brainstem suppression from opioids, not anxiety — the client needs ventilatory rescue and naloxone."}',
  deep_rationale_authored_at = unixepoch()
WHERE id = 'mb1341-n015';
