"""Append 20 high-yield drugs across underrepresented classes to the seed.

Idempotent: skips ids that already exist; sorts cards by id on write.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SEED = ROOT / "packages" / "content" / "drug-cards-seed.json"

NEW_CARDS = [
    {
        "id": "propofol",
        "generic_name": "Propofol",
        "brand_names": "Diprivan",
        "drug_class": "Anesthetic - sedative-hypnotic",
        "mechanism": "GABA-A receptor agonist; rapid loss of consciousness via global CNS depression.",
        "indications": "Induction/maintenance of general anesthesia, ICU sedation.",
        "contraindications": "Egg, soybean, or sulfite allergy. Use caution in hypotension and cardiac instability.",
        "black_box_warning": None,
        "priority_labs": "Triglycerides (with prolonged infusion), CPK, lactate, ABG",
        "patient_teaching": "Will fall asleep quickly. Inform staff about egg/soy allergies. May feel groggy on wakeup.",
        "nursing_implications": "Dedicated IV line. Monitor for hypotension, bradycardia, and propofol infusion syndrome. Strict aseptic technique.",
        "related_tags": "anesthesia,sedation,icu,critical_care,hypotension",
    },
    {
        "id": "succinylcholine",
        "generic_name": "Succinylcholine",
        "brand_names": "Anectine, Quelicin",
        "drug_class": "Depolarizing neuromuscular blocker",
        "mechanism": "Acts as acetylcholine, prolonged depolarization of motor end-plate causes paralysis.",
        "indications": "Rapid sequence intubation, short procedures requiring muscle relaxation.",
        "contraindications": "Personal/family history of malignant hyperthermia, hyperkalemia, burns >24h, recent stroke or spinal cord injury.",
        "black_box_warning": "Cardiac arrest in pediatric patients with undiagnosed myopathy; risk of malignant hyperthermia.",
        "priority_labs": "Potassium, CK, ABG",
        "patient_teaching": "Used during intubation - you will not remember it.",
        "nursing_implications": "Have dantrolene ready for malignant hyperthermia. Monitor train-of-four. Brief duration (5-10 min).",
        "related_tags": "anesthesia,paralytic,intubation,rsi,malignant_hyperthermia,hyperkalemia",
    },
    {
        "id": "lidocaine",
        "generic_name": "Lidocaine",
        "brand_names": "Xylocaine",
        "drug_class": "Class IB antiarrhythmic / local anesthetic",
        "mechanism": "Blocks fast sodium channels; shortens action potential and refractory period in ventricular tissue.",
        "indications": "Ventricular dysrhythmias (V-tach with pulse, V-fib), local/regional anesthesia.",
        "contraindications": "AV block (without pacing), Stokes-Adams syndrome, hypersensitivity.",
        "black_box_warning": None,
        "priority_labs": "Lidocaine level (1.5-5 mcg/mL), liver function (metabolism)",
        "patient_teaching": "If used for procedure, area will be numb. Report any chest pain, dizziness, or tingling around mouth.",
        "nursing_implications": "Toxicity: tinnitus, perioral numbness, seizures. Cardiac monitor with IV infusion. Reduce dose in elderly and liver failure.",
        "related_tags": "antiarrhythmic,local_anesthetic,vtach,vfib,toxicity,cardiology",
    },
    {
        "id": "normal-saline",
        "generic_name": "0.9% Sodium chloride (Normal saline)",
        "brand_names": "NS, 0.9% NaCl",
        "drug_class": "Isotonic IV crystalloid",
        "mechanism": "Replenishes extracellular fluid volume; matches plasma tonicity.",
        "indications": "Hypovolemia, hemorrhagic shock, hyponatremia, IV access maintenance.",
        "contraindications": "Caution with CHF, edema, hypernatremia, severe renal impairment.",
        "black_box_warning": None,
        "priority_labs": "Sodium, chloride, BUN/creatinine, hemoglobin",
        "patient_teaching": "Will receive fluid via IV. Notify nurse for shortness of breath or swelling.",
        "nursing_implications": "Monitor for fluid overload (crackles, JVD, edema). Hyperchloremic acidosis with large volumes.",
        "related_tags": "iv_fluids,hypovolemia,shock,crystalloid,fluid_resuscitation,critical_care",
    },
    {
        "id": "lactated-ringers",
        "generic_name": "Lactated Ringer's",
        "brand_names": "LR, Hartmann's solution",
        "drug_class": "Isotonic balanced IV crystalloid",
        "mechanism": "Provides volume + electrolytes (Na, K, Ca, Cl, lactate); lactate converted to bicarbonate buffers acidemia.",
        "indications": "Volume resuscitation (especially burns, surgery), mild metabolic acidosis.",
        "contraindications": "Liver failure (cannot metabolize lactate), severe hyperkalemia, lactic acidosis.",
        "black_box_warning": None,
        "priority_labs": "Potassium, calcium, sodium, lactate",
        "patient_teaching": "Replaces lost body fluids. Report swelling or trouble breathing.",
        "nursing_implications": "Do not co-administer with ceftriaxone (calcium precipitate). Watch for fluid overload + hyperkalemia in renal failure.",
        "related_tags": "iv_fluids,burns,surgery,resuscitation,crystalloid,acidosis",
    },
    {
        "id": "cisplatin",
        "generic_name": "Cisplatin",
        "brand_names": "Platinol",
        "drug_class": "Platinum-based antineoplastic",
        "mechanism": "Crosslinks DNA strands, inhibiting replication and triggering apoptosis.",
        "indications": "Testicular, ovarian, bladder, lung, head/neck cancers.",
        "contraindications": "Significant renal impairment, hearing loss, peripheral neuropathy.",
        "black_box_warning": "Severe nephrotoxicity, ototoxicity, myelosuppression, anaphylaxis.",
        "priority_labs": "Creatinine, magnesium, potassium, CBC, audiometry",
        "patient_teaching": "Drink plenty of fluids. Report hearing changes, tingling in hands/feet, decreased urine.",
        "nursing_implications": "Pre-hydrate with IV fluids + mannitol. Antiemetic prophylaxis (5-HT3 + dexamethasone). Monitor creatinine daily.",
        "related_tags": "chemo,antineoplastic,nephrotoxicity,ototoxicity,oncology,nausea",
    },
    {
        "id": "methotrexate-oncology",
        "generic_name": "Methotrexate (high-dose)",
        "brand_names": "Trexall, Otrexup",
        "drug_class": "Antimetabolite chemotherapy / DMARD",
        "mechanism": "Inhibits dihydrofolate reductase, blocking DNA/RNA synthesis. Folic acid antagonist.",
        "indications": "Leukemia, lymphoma, rheumatoid arthritis, psoriasis, ectopic pregnancy.",
        "contraindications": "Pregnancy (Category X), severe renal/hepatic impairment, bone marrow suppression.",
        "black_box_warning": "Hepatotoxicity, severe myelosuppression, pulmonary toxicity, fatal if misdosed (weekly vs daily).",
        "priority_labs": "CBC, creatinine, LFTs, methotrexate level (high-dose)",
        "patient_teaching": "Take EXACTLY as prescribed - typically weekly for arthritis. Reliable contraception. Report mouth sores, cough, jaundice.",
        "nursing_implications": "Rescue: leucovorin (folinic acid). Verify weekly vs daily dosing with pharmacy. Monitor for stomatitis, hepatotoxicity.",
        "related_tags": "chemo,antimetabolite,methotrexate,oncology,rheumatoid_arthritis,pregnancy,leucovorin",
    },
    {
        "id": "ondansetron",
        "generic_name": "Ondansetron",
        "brand_names": "Zofran",
        "drug_class": "5-HT3 receptor antagonist (antiemetic)",
        "mechanism": "Selectively blocks serotonin receptors in CTZ and vagal afferents, reducing nausea signaling.",
        "indications": "Chemo-induced nausea, postop nausea, hyperemesis gravidarum.",
        "contraindications": "Congenital long QT syndrome, concurrent apomorphine.",
        "black_box_warning": None,
        "priority_labs": "EKG (QT interval), magnesium, potassium",
        "patient_teaching": "Dissolves on tongue (ODT form). Report irregular heartbeat or fainting.",
        "nursing_implications": "Monitor QT prolongation, especially with electrolyte imbalance. Headache and constipation common.",
        "related_tags": "antiemetic,nausea,chemo,postop,qt_prolongation,5ht3",
    },
    {
        "id": "ethinyl-norgestimate",
        "generic_name": "Ethinyl estradiol / norgestimate",
        "brand_names": "Ortho Tri-Cyclen, TriNessa",
        "drug_class": "Combined oral contraceptive (estrogen + progestin)",
        "mechanism": "Suppresses ovulation via negative feedback on FSH/LH; thickens cervical mucus.",
        "indications": "Contraception, acne, menstrual regulation.",
        "contraindications": "Pregnancy, smokers >35, history of VTE/stroke/MI, breast cancer, active liver disease, uncontrolled HTN.",
        "black_box_warning": "Cardiovascular events in smokers >35.",
        "priority_labs": "Blood pressure, lipid panel, liver enzymes",
        "patient_teaching": "Take at same time daily. Use backup method first cycle. ACHES warning signs: Abdominal pain, Chest pain, Headaches, Eye changes, Severe leg pain.",
        "nursing_implications": "Screen for smoking + clot history. No effect on STI prevention. Antibiotics may reduce effectiveness.",
        "related_tags": "contraceptive,estrogen,progestin,vte,smoking,reproductive,maternity",
    },
    {
        "id": "medroxyprogesterone",
        "generic_name": "Medroxyprogesterone (depot)",
        "brand_names": "Depo-Provera",
        "drug_class": "Progestin-only contraceptive (long-acting)",
        "mechanism": "Suppresses ovulation; thickens cervical mucus; thins endometrium.",
        "indications": "Long-acting contraception, endometriosis, abnormal uterine bleeding.",
        "contraindications": "Pregnancy, undiagnosed vaginal bleeding, breast cancer, severe liver disease.",
        "black_box_warning": "Bone mineral density loss with long-term use - limit to 2 years if possible.",
        "priority_labs": "Bone density (DEXA), weight, blood pressure",
        "patient_teaching": "IM injection every 12 weeks. Take calcium and vitamin D. Fertility return may delay 12-18 months after discontinuation.",
        "nursing_implications": "Z-track or deep IM. Do not massage site. Counsel on weight gain, irregular bleeding, mood changes.",
        "related_tags": "contraceptive,progestin,depo,bone_density,reproductive,maternity",
    },
    {
        "id": "cyclosporine",
        "generic_name": "Cyclosporine",
        "brand_names": "Sandimmune, Neoral, Gengraf",
        "drug_class": "Calcineurin inhibitor immunosuppressant",
        "mechanism": "Inhibits calcineurin → blocks T-cell activation and IL-2 production.",
        "indications": "Solid organ transplant rejection prevention, severe psoriasis, RA.",
        "contraindications": "Uncontrolled HTN, malignancy, concurrent live vaccines.",
        "black_box_warning": "Lymphoma and skin malignancies, severe infection, nephrotoxicity, infusion reactions.",
        "priority_labs": "Cyclosporine trough level, creatinine, magnesium, potassium, BP",
        "patient_teaching": "Take exactly at same times. Avoid grapefruit juice. Avoid live vaccines. Use sun protection. Report tremor, swelling, decreased urine.",
        "nursing_implications": "Many drug interactions (CYP3A4). Monitor for nephrotoxicity, gingival hyperplasia, hirsutism. No grapefruit.",
        "related_tags": "immunosuppressant,transplant,nephrotoxicity,grapefruit,cyp3a4,calcineurin",
    },
    {
        "id": "tacrolimus",
        "generic_name": "Tacrolimus",
        "brand_names": "Prograf, Astagraf",
        "drug_class": "Calcineurin inhibitor immunosuppressant",
        "mechanism": "Binds FKBP-12 → inhibits calcineurin → blocks T-cell activation.",
        "indications": "Transplant rejection prevention (kidney, liver, heart), refractory autoimmune disease.",
        "contraindications": "Hypersensitivity to macrolides or polyoxyl 60 hydrogenated castor oil.",
        "black_box_warning": "Lymphoma + skin malignancies, severe infection, nephrotoxicity, neurotoxicity.",
        "priority_labs": "Tacrolimus trough, creatinine, potassium, glucose, magnesium",
        "patient_teaching": "Same times daily, with or without food but be consistent. Avoid grapefruit. Use contraception. Report tremor, headache, weight gain.",
        "nursing_implications": "Narrow therapeutic index. Monitor for new-onset diabetes, hypertension, neurotoxicity. No grapefruit/St. John's wort.",
        "related_tags": "immunosuppressant,transplant,nephrotoxicity,grapefruit,cyp3a4,diabetes,calcineurin",
    },
    {
        "id": "azathioprine",
        "generic_name": "Azathioprine",
        "brand_names": "Imuran, Azasan",
        "drug_class": "Purine antimetabolite immunosuppressant",
        "mechanism": "Metabolized to 6-mercaptopurine which inhibits purine synthesis → blocks lymphocyte proliferation.",
        "indications": "Transplant rejection, severe RA, inflammatory bowel disease, lupus nephritis.",
        "contraindications": "Pregnancy (some forms), TPMT deficiency, severe infection.",
        "black_box_warning": "Increased risk of lymphoma and skin cancer.",
        "priority_labs": "CBC (especially WBC), LFTs, TPMT genotype, amylase/lipase",
        "patient_teaching": "Take with food to reduce GI upset. Avoid live vaccines. Use sun protection. Report sore throat, fever, easy bruising.",
        "nursing_implications": "Allopurinol increases toxicity (reduce dose 75%). Monitor for myelosuppression and pancreatitis.",
        "related_tags": "immunosuppressant,transplant,myelosuppression,lymphoma,allopurinol,ibd",
    },
    {
        "id": "phenytoin",
        "generic_name": "Phenytoin",
        "brand_names": "Dilantin",
        "drug_class": "Hydantoin anticonvulsant",
        "mechanism": "Stabilizes neuronal membranes by inhibiting sodium influx, raising seizure threshold.",
        "indications": "Tonic-clonic and partial seizures, status epilepticus, trigeminal neuralgia.",
        "contraindications": "Sinus bradycardia, AV block, porphyria.",
        "black_box_warning": "IV cardiovascular collapse if infused too rapidly.",
        "priority_labs": "Phenytoin level (10-20 mcg/mL), albumin, CBC, LFTs",
        "patient_teaching": "Take same time daily. Good oral hygiene (gingival hyperplasia). Avoid alcohol. Don't stop abruptly. Stevens-Johnson rash = emergency.",
        "nursing_implications": "IV: max 50 mg/min, dedicated line with saline (precipitates with dextrose). Many drug interactions. Free vs total level in low albumin.",
        "related_tags": "anticonvulsant,seizure,status_epilepticus,gingival_hyperplasia,stevens_johnson,neurology",
    },
    {
        "id": "levetiracetam",
        "generic_name": "Levetiracetam",
        "brand_names": "Keppra",
        "drug_class": "SV2A modulator anticonvulsant",
        "mechanism": "Binds synaptic vesicle protein SV2A, modulating neurotransmitter release. Mechanism partly unclear.",
        "indications": "Partial-onset, myoclonic, and tonic-clonic seizures (adjunctive or monotherapy).",
        "contraindications": "Hypersensitivity. Caution in renal impairment.",
        "black_box_warning": None,
        "priority_labs": "Creatinine (dose adjust), CBC (rare neutropenia)",
        "patient_teaching": "Take consistently. Report behavioral changes, depression, suicidal thoughts.",
        "nursing_implications": "Well tolerated overall. Watch for irritability/agitation, especially pediatrics. Adjust for renal function.",
        "related_tags": "anticonvulsant,seizure,keppra,depression,renal_dosing,neurology",
    },
    {
        "id": "carbamazepine",
        "generic_name": "Carbamazepine",
        "brand_names": "Tegretol, Carbatrol",
        "drug_class": "Iminostilbene anticonvulsant / mood stabilizer",
        "mechanism": "Sodium channel blockade reducing repetitive neuronal firing.",
        "indications": "Partial seizures, trigeminal neuralgia, bipolar disorder.",
        "contraindications": "Bone marrow suppression, MAOI use within 14 days, hypersensitivity to TCAs.",
        "black_box_warning": "Stevens-Johnson syndrome (HLA-B*1502 in Asian ancestry), aplastic anemia, agranulocytosis.",
        "priority_labs": "Carbamazepine level (4-12 mcg/mL), CBC, LFTs, sodium (SIADH), HLA-B*1502 in at-risk ethnicities",
        "patient_teaching": "Take with food. Report rash, fever, easy bruising, dark urine. Avoid grapefruit. Use sunscreen.",
        "nursing_implications": "Auto-induces own metabolism. Many CYP interactions. SIADH risk - monitor sodium.",
        "related_tags": "anticonvulsant,seizure,trigeminal_neuralgia,stevens_johnson,siadh,bipolar,neurology",
    },
    {
        "id": "levodopa-carbidopa",
        "generic_name": "Levodopa / carbidopa",
        "brand_names": "Sinemet",
        "drug_class": "Dopamine precursor (antiparkinsonian)",
        "mechanism": "Levodopa crosses BBB and is converted to dopamine. Carbidopa blocks peripheral conversion to reduce side effects.",
        "indications": "Parkinson's disease, parkinsonism symptoms.",
        "contraindications": "Narrow-angle glaucoma, melanoma, MAOI within 14 days.",
        "black_box_warning": None,
        "priority_labs": "CBC, LFTs (long-term)",
        "patient_teaching": "May take weeks for effect. Do not take with high-protein meals (compete for absorption). Don't stop abruptly. May cause dark sweat/urine - harmless.",
        "nursing_implications": "Monitor for 'on-off' phenomenon and dyskinesias. Orthostatic hypotension common. Avoid pyridoxine without carbidopa.",
        "related_tags": "parkinsons,dopamine,levodopa,on_off,dyskinesia,orthostatic,neurology",
    },
    {
        "id": "donepezil",
        "generic_name": "Donepezil",
        "brand_names": "Aricept",
        "drug_class": "Cholinesterase inhibitor (Alzheimer's)",
        "mechanism": "Reversibly inhibits acetylcholinesterase → increases ACh in brain, improving cognition.",
        "indications": "Mild to severe Alzheimer's dementia.",
        "contraindications": "Hypersensitivity to piperidines.",
        "black_box_warning": None,
        "priority_labs": "Weight, heart rate, EKG (QT)",
        "patient_teaching": "Take at bedtime. Modest benefit - won't reverse disease. Report fainting, abnormal heartbeat, GI bleeding.",
        "nursing_implications": "Bradycardia and syncope risk. GI side effects (nausea, diarrhea) common at start. Weight loss possible.",
        "related_tags": "alzheimers,dementia,cholinesterase,bradycardia,neurology,geriatric",
    },
    {
        "id": "magnesium-sulfate-ob",
        "generic_name": "Magnesium sulfate (OB)",
        "brand_names": "MgSO4",
        "drug_class": "Anticonvulsant / tocolytic / electrolyte",
        "mechanism": "CNS depressant via NMDA antagonism; smooth muscle relaxation.",
        "indications": "Preeclampsia/eclampsia seizure prophylaxis, preterm labor tocolysis, torsades de pointes.",
        "contraindications": "Heart block, myasthenia gravis, severe renal failure.",
        "black_box_warning": None,
        "priority_labs": "Magnesium level (therapeutic 4-7 mEq/L for OB), creatinine, calcium",
        "patient_teaching": "Will feel warm and flushed. Report difficulty breathing or muscle weakness.",
        "nursing_implications": "Antidote: calcium gluconate. Assess DTRs, RR, urine output q1h. Magnesium toxicity: loss of DTRs (first), respiratory depression, cardiac arrest.",
        "related_tags": "preeclampsia,eclampsia,seizure,tocolytic,magnesium_toxicity,calcium_gluconate,maternity,obstetrics",
    },
    {
        "id": "oxytocin-ob",
        "generic_name": "Oxytocin (OB)",
        "brand_names": "Pitocin, Syntocinon",
        "drug_class": "Uterotonic / posterior pituitary hormone",
        "mechanism": "Binds oxytocin receptors on uterine smooth muscle, stimulating contractions.",
        "indications": "Labor induction/augmentation, postpartum hemorrhage prevention/treatment.",
        "contraindications": "Fetal distress, cephalopelvic disproportion, prior classic C-section, placenta previa.",
        "black_box_warning": "Uterine rupture, fetal/maternal harm with improper use.",
        "priority_labs": "Sodium (water intoxication), fluid balance",
        "patient_teaching": "Will cause stronger contractions. Continuous fetal monitoring required.",
        "nursing_implications": "Piggyback into mainline. Titrate by uterine response. Hold for tachysystole (>5 contractions in 10 min) or non-reassuring FHR.",
        "related_tags": "oxytocin,pitocin,labor_induction,postpartum_hemorrhage,uterine_rupture,obstetrics,maternity",
    },
]

with open(SEED, "r", encoding="utf-8") as f:
    data = json.load(f)

existing_ids = {c["id"] for c in data["cards"]}
added = 0
for card in NEW_CARDS:
    if card["id"] in existing_ids:
        continue
    data["cards"].append(card)
    added += 1

data["cards"].sort(key=lambda c: c["id"])
data["notes"] = (
    "Expanded to 32 high-yield NCLEX drugs. Covers cardiology, anticoagulants, "
    "opioids, antibiotics, anesthesia, IV fluids, oncology, contraceptives, "
    "immunosuppressants, neurology, and OB. The seed script is idempotent "
    "(ON CONFLICT DO UPDATE) so re-running it patches existing rows."
)

with open(SEED, "w", encoding="utf-8", newline="\n") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write("\n")

print(f"Added {added} new cards. Total cards: {len(data['cards'])}.")
