export interface StateData {
  slug: string;
  name: string;
  abbreviation: string;
  boardName: string;
  boardUrl: string;
  ceHoursPerRenewal: number;
  renewalYears: number;
  feeUsd: number;
  fingerprintRequired: boolean;
  nlcCompact: boolean;
  notes?: string;
}

export const STATES: StateData[] = [
  { slug: "alabama", name: "Alabama", abbreviation: "AL", boardName: "Alabama Board of Nursing", boardUrl: "https://www.abn.alabama.gov", ceHoursPerRenewal: 24, renewalYears: 2, feeUsd: 200, fingerprintRequired: true, nlcCompact: true },
  { slug: "alaska", name: "Alaska", abbreviation: "AK", boardName: "Alaska Board of Nursing", boardUrl: "https://www.commerce.alaska.gov/web/cbpl/professionallicensing/boardofnursing.aspx", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 275, fingerprintRequired: true, nlcCompact: false },
  { slug: "arizona", name: "Arizona", abbreviation: "AZ", boardName: "Arizona State Board of Nursing", boardUrl: "https://www.azbn.gov", ceHoursPerRenewal: 0, renewalYears: 4, feeUsd: 200, fingerprintRequired: true, nlcCompact: true, notes: "No CE required; demonstrate competency through practice." },
  { slug: "arkansas", name: "Arkansas", abbreviation: "AR", boardName: "Arkansas State Board of Nursing", boardUrl: "https://www.arsbn.org", ceHoursPerRenewal: 15, renewalYears: 2, feeUsd: 150, fingerprintRequired: true, nlcCompact: true },
  { slug: "california", name: "California", abbreviation: "CA", boardName: "California Board of Registered Nursing", boardUrl: "https://www.rn.ca.gov", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 350, fingerprintRequired: true, nlcCompact: false, notes: "California is not an NLC compact state. CA RNs need additional licenses to practice in other states." },
  { slug: "colorado", name: "Colorado", abbreviation: "CO", boardName: "Colorado Board of Nursing", boardUrl: "https://dpo.colorado.gov/Nursing", ceHoursPerRenewal: 0, renewalYears: 2, feeUsd: 110, fingerprintRequired: true, nlcCompact: true, notes: "No CE required for renewal." },
  { slug: "connecticut", name: "Connecticut", abbreviation: "CT", boardName: "Connecticut Board of Examiners for Nursing", boardUrl: "https://portal.ct.gov/DPH/Practitioner-Licensing--Investigations/RN", ceHoursPerRenewal: 0, renewalYears: 1, feeUsd: 105, fingerprintRequired: false, nlcCompact: false },
  { slug: "delaware", name: "Delaware", abbreviation: "DE", boardName: "Delaware Board of Nursing", boardUrl: "https://dpr.delaware.gov/boards/nursing", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 116, fingerprintRequired: true, nlcCompact: true },
  { slug: "florida", name: "Florida", abbreviation: "FL", boardName: "Florida Board of Nursing", boardUrl: "https://floridasnursing.gov", ceHoursPerRenewal: 24, renewalYears: 2, feeUsd: 110, fingerprintRequired: true, nlcCompact: true, notes: "FL requires 2 hrs prevention of medical errors, 2 hrs Florida law, 2 hrs human trafficking, 1 hr HIV/AIDS." },
  { slug: "georgia", name: "Georgia", abbreviation: "GA", boardName: "Georgia Board of Nursing", boardUrl: "https://sos.ga.gov/georgia-board-nursing", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 65, fingerprintRequired: true, nlcCompact: true },
  { slug: "hawaii", name: "Hawaii", abbreviation: "HI", boardName: "Hawaii Board of Nursing", boardUrl: "https://cca.hawaii.gov/pvl/boards/nursing", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 165, fingerprintRequired: false, nlcCompact: false },
  { slug: "idaho", name: "Idaho", abbreviation: "ID", boardName: "Idaho Board of Nursing", boardUrl: "https://ibn.idaho.gov", ceHoursPerRenewal: 0, renewalYears: 2, feeUsd: 110, fingerprintRequired: true, nlcCompact: true },
  { slug: "illinois", name: "Illinois", abbreviation: "IL", boardName: "Illinois Department of Financial and Professional Regulation", boardUrl: "https://idfpr.illinois.gov/profs/nursing.html", ceHoursPerRenewal: 20, renewalYears: 2, feeUsd: 65, fingerprintRequired: false, nlcCompact: false },
  { slug: "indiana", name: "Indiana", abbreviation: "IN", boardName: "Indiana State Board of Nursing", boardUrl: "https://www.in.gov/pla/nursing", ceHoursPerRenewal: 0, renewalYears: 2, feeUsd: 50, fingerprintRequired: false, nlcCompact: true },
  { slug: "iowa", name: "Iowa", abbreviation: "IA", boardName: "Iowa Board of Nursing", boardUrl: "https://nursing.iowa.gov", ceHoursPerRenewal: 36, renewalYears: 3, feeUsd: 99, fingerprintRequired: true, nlcCompact: true, notes: "Mandatory training in mandatory reporter, abuse identification." },
  { slug: "kansas", name: "Kansas", abbreviation: "KS", boardName: "Kansas State Board of Nursing", boardUrl: "https://ksbn.kansas.gov", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 65, fingerprintRequired: true, nlcCompact: true },
  { slug: "kentucky", name: "Kentucky", abbreviation: "KY", boardName: "Kentucky Board of Nursing", boardUrl: "https://kbn.ky.gov", ceHoursPerRenewal: 14, renewalYears: 1, feeUsd: 65, fingerprintRequired: true, nlcCompact: true, notes: "Includes mandatory 1.5 hrs domestic violence, 1.5 hrs pediatric abusive head trauma, 2 hrs suicide prevention." },
  { slug: "louisiana", name: "Louisiana", abbreviation: "LA", boardName: "Louisiana State Board of Nursing", boardUrl: "https://www.lsbn.state.la.us", ceHoursPerRenewal: 30, renewalYears: 1, feeUsd: 100, fingerprintRequired: true, nlcCompact: true },
  { slug: "maine", name: "Maine", abbreviation: "ME", boardName: "Maine State Board of Nursing", boardUrl: "https://www.maine.gov/boardofnursing", ceHoursPerRenewal: 0, renewalYears: 2, feeUsd: 75, fingerprintRequired: false, nlcCompact: true },
  { slug: "maryland", name: "Maryland", abbreviation: "MD", boardName: "Maryland Board of Nursing", boardUrl: "https://mbon.maryland.gov", ceHoursPerRenewal: 0, renewalYears: 2, feeUsd: 100, fingerprintRequired: true, nlcCompact: true },
  { slug: "massachusetts", name: "Massachusetts", abbreviation: "MA", boardName: "Massachusetts Board of Registration in Nursing", boardUrl: "https://www.mass.gov/orgs/board-of-registration-in-nursing", ceHoursPerRenewal: 15, renewalYears: 2, feeUsd: 120, fingerprintRequired: false, nlcCompact: false, notes: "Required CE in domestic violence, end-of-life care, mandatory reporting." },
  { slug: "michigan", name: "Michigan", abbreviation: "MI", boardName: "Michigan Board of Nursing", boardUrl: "https://www.michigan.gov/lara/bureau-list/bpl/health/hp-lic-health-prof/nursing", ceHoursPerRenewal: 25, renewalYears: 2, feeUsd: 75, fingerprintRequired: false, nlcCompact: false, notes: "Includes mandatory 1 hr pain and pain symptom management, 2 hrs implicit bias, 1 hr human trafficking." },
  { slug: "minnesota", name: "Minnesota", abbreviation: "MN", boardName: "Minnesota Board of Nursing", boardUrl: "https://mn.gov/boards/nursing", ceHoursPerRenewal: 24, renewalYears: 2, feeUsd: 88, fingerprintRequired: false, nlcCompact: false },
  { slug: "mississippi", name: "Mississippi", abbreviation: "MS", boardName: "Mississippi Board of Nursing", boardUrl: "https://www.msbn.ms.gov", ceHoursPerRenewal: 0, renewalYears: 2, feeUsd: 100, fingerprintRequired: true, nlcCompact: true },
  { slug: "missouri", name: "Missouri", abbreviation: "MO", boardName: "Missouri State Board of Nursing", boardUrl: "https://pr.mo.gov/nursing.asp", ceHoursPerRenewal: 0, renewalYears: 2, feeUsd: 80, fingerprintRequired: true, nlcCompact: true },
  { slug: "montana", name: "Montana", abbreviation: "MT", boardName: "Montana Board of Nursing", boardUrl: "https://boards.bsd.dli.mt.gov/nur", ceHoursPerRenewal: 24, renewalYears: 2, feeUsd: 100, fingerprintRequired: true, nlcCompact: true },
  { slug: "nebraska", name: "Nebraska", abbreviation: "NE", boardName: "Nebraska Board of Nursing", boardUrl: "https://dhhs.ne.gov/licensure/Pages/Nurse-Licensing.aspx", ceHoursPerRenewal: 20, renewalYears: 2, feeUsd: 123, fingerprintRequired: true, nlcCompact: true },
  { slug: "nevada", name: "Nevada", abbreviation: "NV", boardName: "Nevada State Board of Nursing", boardUrl: "https://nevadanursingboard.org", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 130, fingerprintRequired: true, nlcCompact: false, notes: "Required CE in bioterrorism (4 hrs once)." },
  { slug: "new-hampshire", name: "New Hampshire", abbreviation: "NH", boardName: "New Hampshire Board of Nursing", boardUrl: "https://www.oplc.nh.gov/board-nursing", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 120, fingerprintRequired: true, nlcCompact: true },
  { slug: "new-jersey", name: "New Jersey", abbreviation: "NJ", boardName: "New Jersey Board of Nursing", boardUrl: "https://www.njconsumeraffairs.gov/nur", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 120, fingerprintRequired: true, nlcCompact: true, notes: "Mandatory 1 hr prescription opioid drugs, 1 hr organ and tissue donation." },
  { slug: "new-mexico", name: "New Mexico", abbreviation: "NM", boardName: "New Mexico Board of Nursing", boardUrl: "https://nmbon.sks.com", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 110, fingerprintRequired: true, nlcCompact: true },
  { slug: "new-york", name: "New York", abbreviation: "NY", boardName: "New York State Education Department, Office of the Professions", boardUrl: "https://www.op.nysed.gov/professions/registered-professional-nursing", ceHoursPerRenewal: 3, renewalYears: 3, feeUsd: 143, fingerprintRequired: false, nlcCompact: false, notes: "NY requires 3 hrs in infection control every 4 years and mandatory child abuse training." },
  { slug: "north-carolina", name: "North Carolina", abbreviation: "NC", boardName: "North Carolina Board of Nursing", boardUrl: "https://www.ncbon.com", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 100, fingerprintRequired: false, nlcCompact: true },
  { slug: "north-dakota", name: "North Dakota", abbreviation: "ND", boardName: "North Dakota Board of Nursing", boardUrl: "https://www.ndbon.org", ceHoursPerRenewal: 12, renewalYears: 2, feeUsd: 130, fingerprintRequired: true, nlcCompact: true },
  { slug: "ohio", name: "Ohio", abbreviation: "OH", boardName: "Ohio Board of Nursing", boardUrl: "https://nursing.ohio.gov", ceHoursPerRenewal: 24, renewalYears: 2, feeUsd: 65, fingerprintRequired: true, nlcCompact: true, notes: "Required 1 hr Ohio Nurse Practice Act content." },
  { slug: "oklahoma", name: "Oklahoma", abbreviation: "OK", boardName: "Oklahoma Board of Nursing", boardUrl: "https://www.ok.gov/nursing", ceHoursPerRenewal: 24, renewalYears: 2, feeUsd: 85, fingerprintRequired: true, nlcCompact: true },
  { slug: "oregon", name: "Oregon", abbreviation: "OR", boardName: "Oregon State Board of Nursing", boardUrl: "https://www.oregon.gov/osbn", ceHoursPerRenewal: 7, renewalYears: 2, feeUsd: 165, fingerprintRequired: true, nlcCompact: false, notes: "Includes 7 hrs pain management once at first renewal." },
  { slug: "pennsylvania", name: "Pennsylvania", abbreviation: "PA", boardName: "Pennsylvania State Board of Nursing", boardUrl: "https://www.dos.pa.gov/ProfessionalLicensing/BoardsCommissions/Nursing", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 122, fingerprintRequired: false, nlcCompact: true, notes: "2 hrs child abuse recognition and reporting required." },
  { slug: "rhode-island", name: "Rhode Island", abbreviation: "RI", boardName: "Rhode Island Board of Nurse Registration and Nursing Education", boardUrl: "https://health.ri.gov/licenses/detail.php?id=232", ceHoursPerRenewal: 10, renewalYears: 2, feeUsd: 135, fingerprintRequired: false, nlcCompact: true },
  { slug: "south-carolina", name: "South Carolina", abbreviation: "SC", boardName: "South Carolina Board of Nursing", boardUrl: "https://www.llr.sc.gov/nurse", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 100, fingerprintRequired: true, nlcCompact: true },
  { slug: "south-dakota", name: "South Dakota", abbreviation: "SD", boardName: "South Dakota Board of Nursing", boardUrl: "https://doh.sd.gov/boards/nursing", ceHoursPerRenewal: 0, renewalYears: 2, feeUsd: 125, fingerprintRequired: true, nlcCompact: true },
  { slug: "tennessee", name: "Tennessee", abbreviation: "TN", boardName: "Tennessee Board of Nursing", boardUrl: "https://www.tn.gov/health/health-program-areas/health-professional-boards/nursing-board.html", ceHoursPerRenewal: 0, renewalYears: 2, feeUsd: 110, fingerprintRequired: true, nlcCompact: true },
  { slug: "texas", name: "Texas", abbreviation: "TX", boardName: "Texas Board of Nursing", boardUrl: "https://www.bon.texas.gov", ceHoursPerRenewal: 20, renewalYears: 2, feeUsd: 70, fingerprintRequired: true, nlcCompact: true, notes: "Required 2 hrs nursing jurisprudence/ethics, 2 hrs older adult/geriatric care for some practice areas." },
  { slug: "utah", name: "Utah", abbreviation: "UT", boardName: "Utah Division of Occupational and Professional Licensing", boardUrl: "https://dopl.utah.gov/nurse", ceHoursPerRenewal: 30, renewalYears: 2, feeUsd: 88, fingerprintRequired: true, nlcCompact: true },
  { slug: "vermont", name: "Vermont", abbreviation: "VT", boardName: "Vermont Board of Nursing", boardUrl: "https://sos.vermont.gov/nursing", ceHoursPerRenewal: 0, renewalYears: 2, feeUsd: 100, fingerprintRequired: false, nlcCompact: true },
  { slug: "virginia", name: "Virginia", abbreviation: "VA", boardName: "Virginia Board of Nursing", boardUrl: "https://www.dhp.virginia.gov/Boards/Nursing", ceHoursPerRenewal: 0, renewalYears: 2, feeUsd: 140, fingerprintRequired: true, nlcCompact: true, notes: "Practice hours required (640 hrs in 5 years OR continuing competence)." },
  { slug: "washington", name: "Washington", abbreviation: "WA", boardName: "Washington State Nursing Care Quality Assurance Commission", boardUrl: "https://www.doh.wa.gov/LicensesPermitsandCertificates/NursingCommission", ceHoursPerRenewal: 45, renewalYears: 3, feeUsd: 116, fingerprintRequired: true, nlcCompact: false, notes: "Requires 6 hrs suicide assessment training, 1 hr health equity, 1 hr LGBTQ training." },
  { slug: "west-virginia", name: "West Virginia", abbreviation: "WV", boardName: "West Virginia Board of Examiners for Registered Professional Nurses", boardUrl: "https://wvrnboard.wv.gov", ceHoursPerRenewal: 12, renewalYears: 1, feeUsd: 75, fingerprintRequired: true, nlcCompact: true },
  { slug: "wisconsin", name: "Wisconsin", abbreviation: "WI", boardName: "Wisconsin Board of Nursing", boardUrl: "https://dsps.wi.gov/Pages/Professions/RN/Default.aspx", ceHoursPerRenewal: 0, renewalYears: 2, feeUsd: 82, fingerprintRequired: false, nlcCompact: true },
  { slug: "wyoming", name: "Wyoming", abbreviation: "WY", boardName: "Wyoming State Board of Nursing", boardUrl: "https://nursing-online.state.wy.us", ceHoursPerRenewal: 20, renewalYears: 2, feeUsd: 130, fingerprintRequired: true, nlcCompact: true },
];

export function getStateBySlug(slug: string): StateData | undefined {
  return STATES.find((s) => s.slug === slug);
}
