-- Premium editorial pass batch 008.
-- Manual source-backed promotions from the generated review queue.
-- No schema, Stripe, auth, UI, layout, CSS, or navigation changes.

UPDATE questions
SET publish_state='published',
    review_status='final-curated-live',
    rationale='The glucose is 55 mg/dL with adrenergic and neuroglycopenic symptoms. If the client is awake and able to swallow safely, the priority is 15 grams of fast-acting oral carbohydrate, followed by repeat glucose assessment.',
    deep_rationale='Hypoglycemia causes both autonomic symptoms, such as shakiness and sweating, and neuroglycopenic symptoms, such as confusion, because the brain depends on circulating glucose. A glucose of 55 mg/dL is clinically significant and needs immediate correction before a dietary-history review or routine teaching. Oral fast-acting carbohydrate is the least invasive and appropriate first intervention when the client is awake and can swallow safely. Glucagon is reserved for severe hypoglycemia when the client is unconscious, having a seizure, or unable to take oral carbohydrate. IV dextrose is also appropriate when oral intake is unsafe or IV rescue is needed, but this option is more invasive than oral carbohydrate for a client who can swallow. Clinical pearl: treat the low first, reassess in about 15 minutes, and never give oral carbohydrate to a client who cannot protect the airway.',
    references_json='[{"title":"NIDDK - Low Blood Glucose (Hypoglycemia)","citation":"NIDDK guidance describes taking 15 to 20 grams of glucose or carbohydrate right away when blood glucose is below target, and discussing glucagon use for emergencies."},{"title":"Endotext, NCBI Bookshelf - Hypoglycemia","citation":"Endotext describes oral glucose or carbohydrate when the patient is able to ingest carbohydrates, with glucagon used in appropriate severe or outpatient rescue situations."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"NCSBN 2026 RN Test Plan, Pharmacological and Parenteral Therapies and Clinical Judgment."}]',
    deep_rationale_authored_at=unixepoch(),
    provenance=COALESCE(provenance,'gen') || '|editorial-batch-008:manual-source-backed-promote'
WHERE id='gen-gemini-1780642824-2-0qczi';

UPDATE questions
SET publish_state='published',
    review_status='final-curated-live',
    rationale='Warfarin teaching must emphasize bleeding surveillance, avoiding aspirin or NSAIDs unless the prescriber approves, and regular INR monitoring. Vitamin K intake should be consistent rather than suddenly increased, and warfarin should not be stopped before procedures without instructions.',
    deep_rationale='Warfarin reduces clot formation by interfering with vitamin K-dependent clotting factors, which creates a narrow balance between preventing thrombosis and causing bleeding. The client should report unusual bleeding such as nosebleeds, gum bleeding, hematuria, melena, or vomiting blood because these may indicate excessive anticoagulation. Aspirin and NSAIDs can increase bleeding risk, so over-the-counter medication use should be cleared with the prescriber or pharmacist. Regular PT/INR monitoring is essential because the dose is adjusted based on anticoagulant effect and bleeding/thrombotic risk. The client should keep vitamin K intake consistent rather than deliberately increasing leafy greens. Minor cuts need firm direct pressure, not warm compresses. Stopping warfarin before dental or surgical procedures must be provider-directed because abrupt interruption can increase clot risk. Clinical pearl: warfarin safety teaching is consistency, INR follow-up, bleeding precautions, and no unsupervised medication changes.',
    references_json='[{"title":"MedlinePlus Drug Information - Warfarin","citation":"MedlinePlus warfarin information describes bleeding risk, INR monitoring, vitamin K food interactions, and the need to tell clinicians about aspirin, NSAIDs, and other medicines."},{"title":"MedlinePlus Medical Encyclopedia - Taking Warfarin","citation":"MedlinePlus patient instructions describe INR testing and bleeding signs such as gum bleeding, blood in urine, dark stool, nosebleeds, or vomiting blood."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"NCSBN 2026 RN Test Plan, Pharmacological and Parenteral Therapies, Reduction of Risk Potential, and Clinical Judgment."}]',
    deep_rationale_authored_at=unixepoch(),
    provenance=COALESCE(provenance,'gen') || '|editorial-batch-008:manual-source-backed-promote'
WHERE id='gen-gemini-1780647321-0-tl6cx';

UPDATE questions
SET publish_state='published',
    review_status='final-curated-live',
    rationale='The client is postictal and lethargic after a first generalized tonic-clonic seizure. Appropriate immediate nursing care includes continuous monitoring, side-lying positioning to protect the airway, and bedside glucose assessment because hypoglycemia can mimic or trigger seizure activity.',
    deep_rationale='After a generalized tonic-clonic seizure, nursing priorities are airway protection, physiologic monitoring, and identifying reversible causes. A lethargic postictal client may have impaired airway reflexes and pooled secretions, so side-lying positioning lowers aspiration risk and helps maintain airway patency. Continuous cardiac and respiratory monitoring is appropriate in the emergency department because seizures and benzodiazepines can affect oxygenation, respiratory drive, rhythm, and hemodynamics. Bedside glucose should be checked quickly because hypoglycemia is a common reversible cause of seizure-like activity and altered mental status. Lorazepam should not be pushed rapidly over 15 seconds because benzodiazepines can worsen respiratory depression and hypotension when administered too quickly. Intubation is not automatically indicated for an oxygen saturation of 94% if the client can maintain ventilation, but airway readiness and reassessment remain important. Clinical pearl: after the convulsion stops, think side, suction/airway readiness, glucose, monitoring, and slow medication administration if ordered.',
    references_json='[{"title":"CDC - First Aid for Seizures","citation":"CDC seizure first aid guidance includes staying with the person, turning them gently on their side when lying down, and watching for trouble breathing or waking after a seizure."},{"title":"MedlinePlus - Seizures","citation":"MedlinePlus seizure resources summarize seizure recognition and first-aid information from the National Library of Medicine."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"NCSBN 2026 RN Test Plan, Physiological Adaptation, Pharmacological and Parenteral Therapies, and Clinical Judgment."}]',
    deep_rationale_authored_at=unixepoch(),
    provenance=COALESCE(provenance,'gen') || '|editorial-batch-008:manual-source-backed-promote'
WHERE id='gen-gemini-1780643721-2-xvy67';
