-- Premium editorial pass batch 011.
-- Manual promotion of high-confidence generated rows after clinical/source review.
-- Backend/data-only: no schema, Stripe, auth, UI, layout, CSS, or navigation changes.

UPDATE questions
SET publish_state='published',
    review_status='final-curated-live',
    references_json=CASE id
      WHEN 'gen-nemotron-1780693222-3-van76' THEN '[{"title":"AHA Guidelines for CPR and Emergency Cardiovascular Care - Acute Coronary Syndromes","citation":"Early aspirin therapy is a core intervention for suspected acute coronary syndrome unless contraindicated."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Pharmacological and Parenteral Therapies; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780677023-3-dy6p6' THEN '[{"title":"MedlinePlus Medical Encyclopedia - Acute adrenal crisis","citation":"Adrenal crisis is an emergency in adrenal insufficiency and may require immediate hydrocortisone injection and supportive treatment."},{"title":"Endotext, NCBI Bookshelf - Adrenal Insufficiency","citation":"Adrenal crisis requires prompt glucocorticoid replacement and fluid resuscitation."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Pharmacological and Parenteral Therapies; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780650024-1-12gii' THEN '[{"title":"Institute for Safe Medication Practices - High-Alert Medications in Acute Care Settings","citation":"Heparin is a high-alert medication that requires prompt safety action when bleeding or excessive anticoagulation occurs."},{"title":"MedlinePlus Drug Information - Heparin Injection","citation":"Heparin can cause serious bleeding and requires urgent clinician notification when bleeding occurs."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Reduction of Risk Potential; Pharmacological and Parenteral Therapies; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780637422-5-zb8hp' THEN '[{"title":"ANA Nursing Scope and Standards of Practice, 4th ed.","citation":"Registered nurses are accountable for recognizing unsafe orders, communicating concerns, and advocating for patient safety."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Management of Care; Safety and Infection Control; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780655425-1-ta7bo' THEN '[{"title":"MedlinePlus Medical Encyclopedia - Gastrointestinal bleeding","citation":"GI bleeding with hypotension, tachycardia, and altered mentation can indicate major blood loss requiring urgent stabilization."},{"title":"StatPearls, NCBI Bookshelf - Hypovolemic Shock","citation":"Initial shock management prioritizes restoration of circulating volume and perfusion."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780731942-1-7w71s' THEN '[{"title":"AHA/ACC/HFSA Guideline for the Management of Heart Failure","citation":"Acute decompensated heart failure can cause pulmonary congestion and hypoxemia requiring prompt oxygenation support."},{"title":"MedlinePlus Medical Encyclopedia - Heart failure","citation":"Heart failure can cause shortness of breath, swelling, and reduced oxygenation from fluid backup."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Basic Care and Comfort; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780730142-1-kt7lo' THEN '[{"title":"StatPearls, NCBI Bookshelf - Hyperkalemia","citation":"Hyperkalemia with ECG changes requires immediate cardiac membrane stabilization with intravenous calcium."},{"title":"AHA Guidelines for CPR and Emergency Cardiovascular Care - Adult Advanced Life Support","citation":"Life-threatening electrolyte disturbances are treated urgently to prevent malignant dysrhythmias."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Pharmacological and Parenteral Therapies; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780700421-3-h9h6f' THEN '[{"title":"MedlinePlus Medical Encyclopedia - SIADH","citation":"SIADH causes low serum sodium from water retention and inappropriately concentrated urine."},{"title":"Endotext, NCBI Bookshelf - Diagnostic Testing for SIADH","citation":"SIADH evaluation uses low serum osmolality with urine that remains concentrated despite hyponatremia."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780691421-5-agyx7' THEN '[{"title":"Brain Trauma Foundation - Guidelines for Severe Traumatic Brain Injury","citation":"ICP care emphasizes head positioning, cerebral perfusion support, osmotic therapy when indicated, and close neurologic and fluid monitoring."},{"title":"StatPearls, NCBI Bookshelf - Increased Intracranial Pressure","citation":"ICP interventions include head elevation, osmotic therapy, and monitoring for perfusion and renal effects."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780701321-1-itz4p' THEN '[{"title":"American Heart Association Scientific Statement - Diagnosis, Treatment, and Long-Term Management of Kawasaki Disease","citation":"Kawasaki disease diagnosis includes fever duration and principal clinical features; coronary artery aneurysm is the major complication."},{"title":"MedlinePlus Medical Encyclopedia - Kawasaki disease","citation":"Kawasaki disease features fever, rash, conjunctivitis, mouth changes, swollen lymph nodes, and risk of coronary artery involvement."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Pediatric Nursing; Clinical Judgment."}]'
      WHEN 'gen-gemini-1780731942-4-hoqrs' THEN '[{"title":"MedlinePlus Drug Information - Lithium","citation":"Lithium toxicity can cause gastrointestinal symptoms, tremor, ataxia, confusion, and requires urgent medical attention."},{"title":"StatPearls, NCBI Bookshelf - Lithium Toxicity","citation":"Moderate-to-severe lithium toxicity requires withholding lithium, urgent evaluation, supportive care, and possible enhanced elimination."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Pharmacological and Parenteral Therapies; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780683321-3-k9i5q' THEN '[{"title":"MedlinePlus Drug Information - Levodopa and Carbidopa","citation":"Levodopa/carbidopa timing and interaction with food or protein can affect symptom control in Parkinson disease."},{"title":"Pharmacology for Nurses, Adams 6th ed.","citation":"Levodopa absorption can be affected by dietary protein and timing, contributing to wearing-off symptoms."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Pharmacological and Parenteral Therapies; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780633820-1-0jm77' THEN '[{"title":"MedlinePlus Medical Encyclopedia - Dehydration","citation":"Infants and children with dehydration may show decreased urination, dry mucous membranes, lethargy, and poor skin turgor."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Pediatric Nursing; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780655425-5-05t8f' THEN '[{"title":"MedlinePlus Medical Encyclopedia - Serotonin syndrome","citation":"Serotonin syndrome can follow serotonergic drug combinations and includes agitation, autonomic instability, tremor, hyperreflexia, and fever."},{"title":"StatPearls, NCBI Bookshelf - Serotonin Syndrome","citation":"Management begins with discontinuing serotonergic agents, supportive care, benzodiazepines when needed, and cyproheptadine in selected cases."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Pharmacological and Parenteral Therapies; Physiological Adaptation; Clinical Judgment."}]'
      ELSE references_json
    END,
    deep_rationale_authored_at=COALESCE(deep_rationale_authored_at, unixepoch()),
    provenance=COALESCE(provenance,'gen') || '|editorial-batch-011:manual-source-backed-promote'
WHERE id IN (
  'gen-nemotron-1780693222-3-van76',
  'gen-nemotron-1780677023-3-dy6p6',
  'gen-nemotron-1780650024-1-12gii',
  'gen-nemotron-1780637422-5-zb8hp',
  'gen-nemotron-1780655425-1-ta7bo',
  'gen-nemotron-1780731942-1-7w71s',
  'gen-nemotron-1780730142-1-kt7lo',
  'gen-nemotron-1780700421-3-h9h6f',
  'gen-nemotron-1780691421-5-agyx7',
  'gen-nemotron-1780701321-1-itz4p',
  'gen-gemini-1780731942-4-hoqrs',
  'gen-nemotron-1780683321-3-k9i5q',
  'gen-nemotron-1780633820-1-0jm77',
  'gen-nemotron-1780655425-5-05t8f'
);
