-- Premium editorial pass batch 010.
-- Manual promotion of high-confidence generated rows after clinical/source review.
-- Backend/data-only: no schema, Stripe, auth, UI, layout, CSS, or navigation changes.

UPDATE questions
SET publish_state='published',
    review_status='final-curated-live',
    references_json=CASE id
      WHEN 'gen-gemini-1780732842-4-qk5n9' THEN '[{"title":"MedlinePlus - Croup","citation":"Croup causes barking cough, stridor, and breathing difficulty from upper-airway inflammation in young children."},{"title":"StatPearls, NCBI Bookshelf - Croup","citation":"Moderate-to-severe croup with stridor may be treated with nebulized racemic epinephrine, with observation for recurrence as effects wear off."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Pediatric Nursing; Clinical Judgment."}]'
      WHEN 'gen-gemini-1780730142-2-aaaof' THEN '[{"title":"MedlinePlus Drug Information - Lactulose","citation":"Lactulose is used to reduce blood ammonia in patients with liver disease."},{"title":"MedlinePlus Medical Encyclopedia - Loss of brain function from liver disease","citation":"Hepatic encephalopathy occurs when the liver cannot remove toxins from blood; lactulose helps prevent intestinal bacteria from creating ammonia."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Pharmacological and Parenteral Therapies; Physiological Adaptation; Clinical Judgment."}]'
      WHEN 'gen-gemini-1780678824-4-39har' THEN '[{"title":"Lewis Medical-Surgical Nursing, 11th ed.","citation":"Fluid volume excess and heart failure assessment includes jugular venous distention, crackles, edema, S3, oxygenation changes, and pulmonary edema cues."},{"title":"AHA/ACC/HFSA Heart Failure Guideline","citation":"Heart failure assessment and management require recognition of congestion, pulmonary edema, and volume-overload findings."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-gemini-1780731042-0-4q472' THEN '[{"title":"Paralyzed Veterans of America - Autonomic Dysreflexia Clinical Practice Guideline","citation":"Autonomic dysreflexia in SCI at or above T6 requires sitting the client upright, loosening constrictive clothing, frequent blood pressure checks, and removing bladder or bowel triggers."},{"title":"MSD Manual Professional - Spinal Cord Autonomic Dysreflexia","citation":"Autonomic dysreflexia is suspected with SCI above T6, severe hypertension, and sympathetic activity often triggered by bladder or bowel distention."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-gemini-1780731942-2-ksax5' THEN '[{"title":"AHRQ - Preventing Falls in Hospitals","citation":"Hospital fall-prevention programs use risk identification, assisted toileting, rounding, mobility support, and individualized prevention planning."},{"title":"NPIAP - Pressure Injury Prevention Points","citation":"Pressure injury prevention includes structured risk assessment, skin assessment, heel protection, pressure redistribution, and attention to bony prominences."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Safety and Infection Control; Basic Care and Comfort; Clinical Judgment."}]'
      WHEN 'gen-gemini-1780732842-2-xr66u' THEN '[{"title":"NIDDK - Low Blood Glucose (Hypoglycemia)","citation":"Low glucose treatment includes 15 to 20 grams of glucose or carbohydrate, then waiting 15 minutes and rechecking glucose."},{"title":"CDC - Treatment of Low Blood Sugar","citation":"The 15-15 approach uses 15 grams of carbohydrate followed by a 15-minute reassessment; glucagon is for severe hypoglycemia when the person cannot safely take oral carbohydrate."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Pharmacological and Parenteral Therapies; Physiological Adaptation; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780665322-5-m8uly' THEN '[{"title":"CDC - C. diff Facts for Clinicians","citation":"Healthcare professionals should wear gloves and gowns when treating patients with potential infectious diarrhea including C. diff; hand sanitizer does not kill C. diff spores."},{"title":"CDC - Preventing C. diff","citation":"C. diff prevention includes soap-and-water hand hygiene after bathroom use and gown/glove precautions for care interactions."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Safety and Infection Control; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780687821-3-nqpbp' THEN '[{"title":"StatPearls, NCBI Bookshelf - Hyperkalemia","citation":"Hyperkalemia with ECG changes requires calcium therapy first to stabilize cardiac membranes."},{"title":"UCSF Hospital Handbook - Hyperkalemia","citation":"Potassium greater than 6.5 mEq/L or hyperkalemia with ECG changes warrants emergent treatment with IV calcium."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Pharmacological and Parenteral Therapies; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780621220-3-khd52' THEN '[{"title":"MedlinePlus Medical Encyclopedia - SIADH","citation":"SIADH causes low serum sodium with concentrated urine; fluid status assessment is important, and treatment often includes fluid restriction."},{"title":"Endotext, NCBI Bookshelf - Endocrine Testing for SIADH","citation":"SIADH involves inappropriate water retention with concentrated urine and may be managed with fluid restriction or other therapy depending on severity."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780685121-3-f4ak9' THEN '[{"title":"VA/DoD Clinical Practice Guideline - Assessment and Management of Patients at Risk for Suicide","citation":"Suicide-risk assessment prioritizes current suicidal ideation, intent, plan, access to lethal means, past behavior, and protective factors."},{"title":"VA Suicide Prevention - Prevention","citation":"Reducing access to firearms or medications and increasing time and distance from lethal means can reduce suicide risk during brief crises."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Psychosocial Integrity; Management of Care; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780612221-3-9b9kl' THEN '[{"title":"Mayo Clinic - Pre-surgery medication titration for pheochromocytoma and paraganglioma","citation":"Preoperative management uses alpha blockade such as phenoxybenzamine or doxazosin; beta blockade is considered only after alpha blockade when tachycardia is present."},{"title":"StatPearls, NCBI Bookshelf - Perioperative Management of Pheochromocytoma","citation":"Alpha blockade is central before pheochromocytoma surgery, and beta blockade should not be initiated before alpha blockade because of unopposed alpha effects."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Pharmacological and Parenteral Therapies; Physiological Adaptation; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780650921-1-qfsc8' THEN '[{"title":"MedlinePlus Medical Encyclopedia - Hemolytic transfusion reaction","citation":"Hemolytic transfusion reactions can cause chills, fever, hemoglobinuria, hypotension, tachycardia, and serious complications."},{"title":"StatPearls, NCBI Bookshelf - Transfusion Reactions","citation":"Respiratory distress, high fever, hypotension, and hemoglobinuria can signal a severe transfusion reaction requiring immediate response."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Reduction of Risk Potential; Physiological Adaptation; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780730142-3-v0k92' THEN '[{"title":"CDC - First Aid for Seizures","citation":"Seizure first aid includes staying with the person, turning them gently on the side if lying down, and watching for trouble breathing or prolonged seizure activity."},{"title":"MedlinePlus - Seizures","citation":"Seizure care includes airway/safety support and emergency evaluation for prolonged or repeated seizures."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780641022-3-hurav' THEN '[{"title":"CDC - Intravascular catheter-related infection prevention strategies","citation":"Central line infection prevention includes hand hygiene, chlorhexidine skin antisepsis, and dressing replacement when dressings are soiled, loose, or compromised."},{"title":"CDC - CLABSI Basics","citation":"Central lines are a serious infection source and require prevention bundles and careful maintenance."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Safety and Infection Control; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780670721-1-bec4t' THEN '[{"title":"MedlinePlus - Dehydration","citation":"Infants and young children with dehydration may show dry mouth, decreased urination, and severe cases may require IV fluids in the hospital."},{"title":"MedlinePlus Medical Encyclopedia - Dehydration","citation":"More severe dehydration may require fluid through a vein; children can lose fluid rapidly with vomiting and diarrhea."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Pediatric Nursing; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780671627-3-dvjnv' THEN '[{"title":"MedlinePlus Medical Encyclopedia - Acute adrenal crisis","citation":"Adrenal crisis is an emergency in adrenal insufficiency and may require hydrocortisone injection when the client is too ill to take oral medication."},{"title":"Endotext, NCBI Bookshelf - Adrenal Insufficiency","citation":"Adrenal crisis requires prompt hydrocortisone and fluid replacement, including isotonic saline and dextrose-containing saline when hypoglycemia is present."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Pharmacological and Parenteral Therapies; Clinical Judgment."}]'
      ELSE references_json
    END,
    rationale=CASE id
      WHEN 'gen-nemotron-1780621220-3-khd52' THEN 'The sodium, serum osmolality, urine sodium, and urine osmolality pattern is consistent with SIADH: dilutional hyponatremia with inappropriately concentrated urine and elevated urine sodium in a clinically euvolemic client. Hypertonic saline is not a blanket initial treatment unless severe neurologic symptoms are present.'
      WHEN 'gen-nemotron-1780685121-3-f4ak9' THEN 'Immediate suicide risk is clarified first by asking whether the client has a specific plan, intent, and access to lethal means. Stressors, past attempts, and support systems matter, but plan plus means determines urgent safety actions.'
      WHEN 'gen-nemotron-1780670721-1-bec4t' THEN 'The child has moderate-to-severe dehydration cues, including lethargy, dry mucous membranes, decreased skin turgor, and low urine output after vomiting and diarrhea. IV access for fluid resuscitation is the priority to restore perfusion and prevent shock.'
      ELSE rationale
    END,
    deep_rationale=CASE id
      WHEN 'gen-nemotron-1780621220-3-khd52' THEN 'SIADH causes excess antidiuretic hormone activity, so the kidneys retain free water despite low serum osmolality. This produces dilutional hyponatremia and neurologic symptoms such as headache or confusion as serum sodium falls. The laboratory pattern supports SIADH because serum sodium and serum osmolality are low while urine remains inappropriately concentrated and urine sodium is elevated. The client is expected to be euvolemic rather than edematous or dehydrated. Hypervolemic hyponatremia would suggest heart failure, cirrhosis, or renal failure, not this classic SIADH pattern. Hypertonic saline is reserved for severe or rapidly worsening neurologic symptoms such as seizures or coma and must be administered carefully to avoid overly rapid sodium correction. Clinical pearl: in hyponatremia questions, match the urine concentration and volume status before choosing treatment.'
      WHEN 'gen-nemotron-1780685121-3-f4ak9' THEN 'A client who reports passive suicidal thoughts still needs immediate risk stratification. The highest-yield first assessment is whether the client has moved from thoughts to a specific plan, has intent, and can access lethal means such as firearms, medications, or other methods. Plan specificity and means access sharply increase short-term danger and determine whether the nurse must initiate continuous observation, environmental safety controls, crisis intervention, or emergency psychiatric evaluation. Recent stressors explain context but do not establish imminent ability to self-harm. A prior attempt is an important lifetime risk factor, but current plan and means guide immediate safety. Social support affects discharge planning and protective factors, but it does not replace direct assessment of intent and access. Clinical pearl: ask plainly about plan, intent, and means; indirect questions miss the information needed to keep the client safe.'
      WHEN 'gen-nemotron-1780670721-1-bec4t' THEN 'Young children can deteriorate quickly from vomiting and diarrhea because they have smaller fluid reserves and higher metabolic needs. This child has multiple dehydration severity cues: lethargy, dry mucous membranes, decreased skin turgor, and urine output at the low end of acceptable perfusion. Lethargy is especially concerning because it can indicate impaired cerebral perfusion or progressing shock. Oral rehydration is appropriate for mild dehydration when the child can drink reliably, but it is not the priority when the child is lethargic and showing signs of moderate-to-severe volume depletion. Establishing IV access allows rapid isotonic fluid replacement, laboratory monitoring, and escalation if perfusion worsens. Checking capillary refill is useful assessment, but it does not correct the intravascular deficit. Clinical pearl: in pediatric dehydration, mental status and perfusion cues move the answer from oral rehydration toward IV fluid resuscitation.'
      ELSE deep_rationale
    END,
    distractor_rationales=CASE id
      WHEN 'gen-gemini-1780732842-4-qk5n9' THEN '{"a":"A short-acting beta agonist treats lower-airway bronchospasm, not the subglottic edema causing barking cough and inspiratory stridor in croup.","c":"Antibiotics do not address typical viral croup and would delay treatment of the upper-airway obstruction cues in the stem.","d":"Viral testing may identify the cause later, but it does not improve airway patency for a restless child with stridor."}'
      ELSE distractor_rationales
    END,
    deep_rationale_authored_at=COALESCE(deep_rationale_authored_at, unixepoch()),
    provenance=COALESCE(provenance,'gen') || '|editorial-batch-010:manual-source-backed-promote'
WHERE id IN (
  'gen-gemini-1780732842-4-qk5n9',
  'gen-gemini-1780730142-2-aaaof',
  'gen-gemini-1780678824-4-39har',
  'gen-gemini-1780731042-0-4q472',
  'gen-gemini-1780731942-2-ksax5',
  'gen-gemini-1780732842-2-xr66u',
  'gen-nemotron-1780665322-5-m8uly',
  'gen-nemotron-1780687821-3-nqpbp',
  'gen-nemotron-1780621220-3-khd52',
  'gen-nemotron-1780685121-3-f4ak9',
  'gen-nemotron-1780612221-3-9b9kl',
  'gen-nemotron-1780650921-1-qfsc8',
  'gen-nemotron-1780730142-3-v0k92',
  'gen-nemotron-1780641022-3-hurav',
  'gen-nemotron-1780670721-1-bec4t',
  'gen-nemotron-1780671627-3-dvjnv'
);
