-- Premium editorial pass batch 007.
-- Manual source-backed promotions from the generated review queue.
-- No schema, Stripe, auth, UI, layout, CSS, or navigation changes.

UPDATE questions
SET publish_state='published',
    review_status='final-curated-live',
    rationale='Routine vital signs, ambulation for a stable cleared postoperative client, and basic hygiene/meal assistance are appropriate CNA tasks. Wound assessment, insulin administration, and A1c interpretation require licensed nursing judgment and cannot be delegated to a CNA.',
    deep_rationale='Delegation questions test whether the RN can separate stable, routine, measurable tasks from work that requires assessment, teaching, medication administration, interpretation, or evaluation. This client is stable on postoperative day 2, so collecting routine vital signs, assisting with ambulation to the bathroom, and helping with oral hygiene and meal setup are appropriate CNA tasks when facility policy and supervision are in place. Assessing a surgical site is not just looking; it requires interpreting redness, drainage, swelling, warmth, and wound risk. Sliding-scale insulin is medication administration with hypoglycemia risk and requires licensed judgment. Interpreting A1c and adjusting insulin are clinical decision-making tasks. Clinical pearl: if the task requires assessment, teaching, evaluation, medication administration, or interpretation of clinical meaning, it stays with the RN or another appropriately licensed clinician.',
    references_json='[{"title":"NCSBN National Guidelines for Nursing Delegation","citation":"NCSBN delegation guidance describes the Five Rights of Delegation and emphasizes that the licensed nurse remains accountable for appropriate task selection, communication, supervision, and evaluation."},{"title":"Nursing Management and Professional Concepts - NCBI Bookshelf","citation":"The NCBI nursing delegation chapter summarizes NCSBN delegation principles, including right task, circumstance, person, direction/communication, and supervision/evaluation."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"NCSBN 2026 RN Test Plan, Management of Care and Clinical Judgment."}]',
    deep_rationale_authored_at=unixepoch(),
    provenance=COALESCE(provenance,'gen') || '|editorial-batch-007:manual-source-backed-promote'
WHERE id='gen-nemotron-1780637422-1-4f73n';

UPDATE questions
SET publish_state='published',
    review_status='final-curated-live',
    rationale='The client has hypovolemic shock from active gastrointestinal bleeding. Priority nursing actions include restoring circulating volume with IV crystalloid while definitive therapy is arranged, keeping the client NPO for endoscopy or airway-risk procedures, and monitoring urine output as a perfusion marker.',
    deep_rationale='Hematemesis, melena, hypotension, tachycardia, low hemoglobin, diaphoresis, and altered mentation point to acute upper gastrointestinal bleeding with shock physiology. The immediate nursing priorities are circulation and preparation for definitive evaluation. IV crystalloid resuscitation supports blood pressure and organ perfusion while blood products, labs, and endoscopic management are being coordinated. NPO status reduces aspiration risk and prepares the client for urgent endoscopy or possible procedural sedation. Hourly urine output helps evaluate renal perfusion and response to resuscitation. A cold pack does not treat intravascular volume loss. Octreotide may be ordered when variceal bleeding is suspected, but the stem does not provide variceal-risk cues and it is not the broad first nursing priority over resuscitation. Oral antacid is inappropriate in an unstable NPO client with active bleeding. Clinical pearl: active GI bleed with hypotension is a circulation problem first; stabilize, prepare for endoscopy, and trend perfusion.',
    references_json='[{"title":"Merck Manual Professional - Overview of Gastrointestinal Bleeding","citation":"Merck Manual Professional describes hematemesis and melena as potential emergencies and includes IV fluid resuscitation as an initial management priority for significant GI bleeding."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"NCSBN 2026 RN Test Plan, Physiological Adaptation, Management of Care, and Clinical Judgment."}]',
    deep_rationale_authored_at=unixepoch(),
    provenance=COALESCE(provenance,'gen') || '|editorial-batch-007:manual-source-backed-promote'
WHERE id='gen-nemotron-1780644622-1-nxvg5';

UPDATE questions
SET publish_state='published',
    review_status='final-curated-live',
    rationale='Ampicillin is a penicillin-class antibiotic, so a known penicillin allergy makes the order unsafe until clarified. The nurse should contact the prescriber, document the communication and resolution, and use the chain of command if the unsafe order is not corrected.',
    deep_rationale='Medication safety requires the nurse to check allergies before administration and to stop when a prescribed medication conflicts with a known allergy. Ampicillin is in the penicillin class, so administering it to a client with a documented penicillin allergy could cause serious hypersensitivity, including anaphylaxis. The first action is direct clarification with the prescribing clinician using clear allergy information. If the prescriber is unavailable or insists on an unsafe order, the nurse must escalate through the chain of command according to facility policy while continuing to protect the client. Documentation should capture the concern, who was contacted, the response, and the final resolution. Administering the medication while watching for a reaction is unsafe because prevention is the goal. Prophylactic diphenhydramine or epinephrine does not make a contraindicated antibiotic safe to give. Clinical pearl: allergy conflict equals stop, clarify, document, and escalate if needed.',
    references_json='[{"title":"ANA 2025 Code of Ethics for Nurses - Provisions","citation":"The ANA Code of Ethics provisions describe the nurse''s duty to advocate for the health and safety of recipients of nursing care and uphold professional accountability."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"NCSBN 2026 RN Test Plan, Pharmacological and Parenteral Therapies, Safety and Infection Control, and Clinical Judgment."}]',
    deep_rationale_authored_at=unixepoch(),
    provenance=COALESCE(provenance,'gen') || '|editorial-batch-007:manual-source-backed-promote'
WHERE id='gen-gemini-1780644622-2-ee6ri';

UPDATE questions
SET publish_state='published',
    review_status='final-curated-live',
    rationale='A fetal heart rate baseline of 130 bpm with moderate variability, accelerations present, and no decelerations is Category I and reassuring. There is no absent variability, late deceleration pattern, or fetal-distress cue requiring immediate intervention.',
    deep_rationale='Category I fetal heart rate tracings are strongly associated with normal fetal acid-base status at the time observed. This strip has a normal baseline rate of 130 bpm, moderate variability, accelerations, and no decelerations. Moderate variability is one of the strongest reassuring features because it reflects intact fetal neurologic and oxygenation status. Accelerations may be present or absent in Category I, but when present they add reassurance. The tracing is not Category II or III because there are no late decelerations, recurrent variable decelerations, bradycardia, tachycardia, or absent variability. The appropriate interpretation is routine ongoing observation rather than immediate intrauterine resuscitation. Clinical pearl: moderate variability plus no late or variable decelerations is reassuring; do not overcall fetal distress when the objective strip is Category I.',
    references_json='[{"title":"AHRQ Perinatal Safety - Electronic Fetal Monitoring","citation":"AHRQ summarizes Category I criteria as baseline 110-160 bpm, moderate variability, accelerations present or absent, and absent late or variable decelerations, with no specific action required."},{"title":"NICHD Workshop Review on Standardized Fetal Heart Rate Nomenclature","citation":"The NICHD three-tier system describes Category I tracings as baseline 110-160 bpm, moderate variability, absent late or variable decelerations, with early decelerations and accelerations either present or absent."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"NCSBN 2026 RN Test Plan, Health Promotion and Maintenance and Clinical Judgment."}]',
    deep_rationale_authored_at=unixepoch(),
    provenance=COALESCE(provenance,'gen') || '|editorial-batch-007:manual-source-backed-promote'
WHERE id='gen-gemini-1780644622-4-5m5wc';

UPDATE questions
SET publish_state='published',
    review_status='final-curated-live',
    rationale='The lithium level is elevated with neurologic and gastrointestinal toxicity signs plus impaired renal clearance. Appropriate actions are to stop lithium, give isotonic IV fluids to support renal elimination, and monitor serial lithium levels.',
    deep_rationale='Lithium has a narrow therapeutic index and is cleared primarily through the kidneys. This client has confusion, tremor, nausea, lithium 2.0 mEq/L, mild hyponatremia, and elevated creatinine, which together suggest toxicity with reduced clearance. The first safety step is to discontinue lithium so the exposure does not continue. Isotonic normal saline supports volume status and renal lithium elimination, especially when sodium depletion or dehydration contributes to lithium retention. Serial lithium levels are needed because tissue redistribution can cause rebound and because treatment decisions depend on trend, symptoms, and renal function. Activated charcoal does not effectively bind lithium because lithium is a small charged metal ion. Direct sodium supplements are not the standard acute treatment; isotonic IV saline addresses volume and sodium physiology more safely. Clinical pearl: lithium toxicity is a renal-clearance problem; stop the drug, hydrate with isotonic saline, monitor levels and neurologic status, and escalate for dialysis when toxicity is severe.',
    references_json='[{"title":"Lithium Toxicity - StatPearls, NCBI Bookshelf","citation":"NCBI Bookshelf describes lithium toxicity management, including that activated charcoal does not effectively adsorb lithium and that hemodialysis is used for severe toxicity or renal failure."},{"title":"Lithium - StatPearls, NCBI Bookshelf","citation":"NCBI Bookshelf describes hydration and discontinuation of lithium as primary management, with normal saline facilitating lithium excretion."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"NCSBN 2026 RN Test Plan, Pharmacological and Parenteral Therapies and Clinical Judgment."}]',
    deep_rationale_authored_at=unixepoch(),
    provenance=COALESCE(provenance,'gen') || '|editorial-batch-007:manual-source-backed-promote'
WHERE id='gen-nemotron-1780643721-5-uyun1';
