-- Premium editorial pass batch 009.
-- Manual promotion of high-confidence generated rows after clinical/source review.
-- Backend/data-only: no schema, Stripe, auth, UI, layout, CSS, or navigation changes.

UPDATE questions
SET publish_state='published',
    review_status='final-curated-live',
    references_json=CASE id
      WHEN 'gen-gemini-1780613121-2-vqmvw' THEN '[{"title":"Lewis Medical-Surgical Nursing, 11th ed.","citation":"Pleural drainage and chest tube nursing care: assess water seal bubbling, tidaling, drainage changes, disconnection, and emergency water-seal safety."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-gemini-1780643721-0-eaw97' THEN '[{"title":"ACLS/AHA Acute Coronary Syndromes guidance","citation":"ACS care prioritizes antiplatelet therapy, symptom control, hemodynamic monitoring, and recognition of nitrate/opioid adverse effects."},{"title":"MedlinePlus - Nitroglycerin","citation":"Nitroglycerin causes vasodilation and may cause headache, dizziness, or hypotension; emergency symptoms require prompt evaluation."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Pharmacological and Parenteral Therapies; Physiological Adaptation; Clinical Judgment."}]'
      WHEN 'gen-gemini-1780669823-4-8xd6t' THEN '[{"title":"ANA Scope and Standards of Practice, 4th ed.","citation":"Registered nurses are accountable for safe medication administration, advocacy, escalation, and collaborative communication when an order may harm a client."},{"title":"ISMP Medication Safety Resources","citation":"ISMP medication safety guidance supports stopping unsafe medication processes and escalating unresolved safety concerns."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Management of Care; Safety and Infection Control; Clinical Judgment."}]'
      WHEN 'gen-gemini-1780652722-0-6lxwt' THEN '[{"title":"NIDDK - Eating and Nutrition for Peritoneal Dialysis","citation":"Peritoneal dialysis nutrition plans may be less strict than hemodialysis but still require individualized attention to sodium, potassium, phosphorus, fluid, and protein needs."},{"title":"NIDDK - Peritoneal Dialysis","citation":"Home peritoneal dialysis requires sterile technique, supply management, and monitoring for complications such as peritonitis and fluid imbalance."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Basic Care and Comfort; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-gemini-1780643721-4-22xop' THEN '[{"title":"MedlinePlus Drug Information - Levodopa and Carbidopa","citation":"MedlinePlus notes interactions with high-protein diet changes and iron products and instructs clients not to crush extended-release formulations."},{"title":"DailyMed - Carbidopa and Levodopa Extended-Release","citation":"DailyMed labeling instructs clients to swallow extended-release products whole and not chew, divide, or crush them."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Pharmacological and Parenteral Therapies; Health Promotion and Maintenance; Clinical Judgment."}]'
      WHEN 'gen-gemini-1780694121-0-4wgd2' THEN '[{"title":"Endotext, NCBI Bookshelf - Hyperosmolar Hyperglycemic State","citation":"HHS evaluation and treatment focus on severe hyperglycemia, hyperosmolality, dehydration, electrolyte monitoring, and fluid resuscitation before or with insulin therapy."},{"title":"American Diabetes Association Standards of Care in Diabetes","citation":"Hospital hyperglycemic crisis management emphasizes fluid replacement, potassium/electrolyte monitoring, insulin therapy, and treatment of precipitating illness."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Pharmacological and Parenteral Therapies; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780614921-5-944cl' THEN '[{"title":"NINDS - Guillain-Barre Syndrome","citation":"NINDS describes immune-mediated peripheral nerve injury, IVIG/plasma exchange treatment, autonomic instability, and potential respiratory failure requiring intensive monitoring."},{"title":"MedlinePlus - Guillain-Barre Syndrome","citation":"MedlinePlus summarizes symptoms, diagnostic findings, and priority treatment/supportive-care needs for Guillain-Barre syndrome."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780680623-5-bbrcx' THEN '[{"title":"KDIGO Clinical Practice Guideline for Acute Kidney Injury","citation":"AKI care includes identifying reversible causes, restoring renal perfusion when hypovolemia is present, and avoiding nephrotoxic exposures."},{"title":"NCBI Bookshelf - Prerenal Kidney Failure","citation":"Prerenal AKI management centers on restoring effective circulating volume and renal perfusion when volume depletion is present."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780614921-1-9usm3' THEN '[{"title":"NIDDK - Nephrotic Syndrome in Adults","citation":"NIDDK lists proteinuria, hypoalbuminemia, edema, and hyperlipidemia as core nephrotic syndrome findings."},{"title":"KDIGO Glomerular Diseases Guideline","citation":"KDIGO glomerular disease guidance addresses nephrotic syndrome complications including thromboembolic risk and proteinuria-related management concerns."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780620320-5-0ubkp' THEN '[{"title":"NINDS - Multiple Sclerosis","citation":"NINDS describes relapse/exacerbation management with corticosteroids such as methylprednisolone over several days and supportive rehabilitation needs."},{"title":"VA Multiple Sclerosis Centers of Excellence - Relapse Treatment","citation":"VA MS relapse guidance notes high-dose corticosteroids and rehabilitation may be used to manage acute relapse effects."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Pharmacological and Parenteral Therapies; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780670721-3-ae3h2' THEN '[{"title":"MedlinePlus Drug Information - Enoxaparin Injection","citation":"MedlinePlus describes enoxaparin bleeding risk, injection teaching, drug interactions, and ordered laboratory monitoring."},{"title":"DailyMed - Lovenox Prescribing Information","citation":"DailyMed labeling includes warnings for bleeding and heparin-induced thrombocytopenia with or without thrombosis."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Pharmacological and Parenteral Therapies; Reduction of Risk Potential; Clinical Judgment."}]'
      WHEN 'gen-nemotron-1780659024-5-lrw50' THEN '[{"title":"ACLS/AHA Acute Coronary Syndromes guidance","citation":"Suspected ACS care includes rapid antiplatelet therapy, ECG-based recognition, oxygen only when clinically indicated, nitrate safety, and pain management."},{"title":"MedlinePlus Medical Encyclopedia - Heart Attack","citation":"MedlinePlus describes myocardial infarction symptoms, emergency response, and medication classes used to reduce clotting and myocardial workload."},{"title":"NCSBN 2026 NCLEX-RN Test Plan","citation":"Physiological Adaptation; Pharmacological and Parenteral Therapies; Clinical Judgment."}]'
      ELSE references_json
    END,
    rationale=CASE id
      WHEN 'gen-nemotron-1780680623-5-bbrcx' THEN 'The client has oliguria, rising creatinine/BUN, tachycardia, and a low CVP after surgery, which is most consistent with prerenal acute kidney injury from reduced effective circulating volume. Restoring intravascular volume with isotonic saline is the priority to improve renal perfusion.'
      ELSE rationale
    END,
    deep_rationale=CASE id
      WHEN 'gen-nemotron-1780680623-5-bbrcx' THEN 'This postoperative client is developing acute kidney injury, shown by oliguria and a sharp creatinine rise from baseline. The low central venous pressure, tachycardia, and postoperative context point toward reduced effective circulating volume rather than intrinsic renal injury as the immediate reversible problem. Prerenal AKI is treated first by restoring renal perfusion when hypovolemia is suspected. An isotonic saline bolus expands intravascular volume, supports cardiac output, and can improve glomerular filtration if the kidney injury is still perfusion-responsive. Furosemide may increase urine output only if adequate circulating volume is present; giving it during volume depletion can worsen renal hypoperfusion. Hemodialysis is reserved for severe or complicated AKI, such as refractory hyperkalemia, severe acidosis, fluid overload, or uremic complications, none of which are the immediate cue here. NSAIDs should be avoided because they can constrict afferent renal blood flow and worsen kidney injury. Clinical pearl: in AKI questions, match the intervention to the cause; low perfusion cues call for volume restoration before diuresis or dialysis.'
      ELSE deep_rationale
    END,
    deep_rationale_authored_at=COALESCE(deep_rationale_authored_at, unixepoch()),
    provenance=COALESCE(provenance,'gen') || '|editorial-batch-009:manual-source-backed-promote'
WHERE id IN (
  'gen-gemini-1780613121-2-vqmvw',
  'gen-gemini-1780643721-0-eaw97',
  'gen-gemini-1780669823-4-8xd6t',
  'gen-gemini-1780652722-0-6lxwt',
  'gen-gemini-1780643721-4-22xop',
  'gen-gemini-1780694121-0-4wgd2',
  'gen-nemotron-1780614921-5-944cl',
  'gen-nemotron-1780680623-5-bbrcx',
  'gen-nemotron-1780614921-1-9usm3',
  'gen-nemotron-1780620320-5-0ubkp',
  'gen-nemotron-1780670721-3-ae3h2',
  'gen-nemotron-1780659024-5-lrw50'
);
