-- Gold-standard premium NGN seed batch (Claude-authored). Diverse subjects + types.
-- SATA + Matrix. Published live. Sets the quality bar for the 5,000-item target.

-- 1. SATA — Sepsis early recognition / Hour-1 bundle (Management of Care)
INSERT OR REPLACE INTO questions (id, exam, type, category, subcategory, difficulty, stem, options, answer, rationale, deep_rationale, distractor_rationales, references_json, tags, publish_state, review_status, deep_rationale_authored_at, created_at)
VALUES (
 'gen-ngn-0001-sepsis-bundle', 'nclex', 'sata', 'sepsis_recognition_bundle', 'Surviving Sepsis Hour-1 Bundle', 4,
 'A 68-year-old client on the medical unit has a temperature of 38.9°C (102°F), heart rate 118/min, respiratory rate 24/min, blood pressure 92/54 mm Hg, and new confusion. The provider suspects sepsis. Which actions should the nurse anticipate completing within the first hour? Select all that apply.',
 '[{"id":"a","text":"Obtain serum lactate level"},{"id":"b","text":"Draw blood cultures before starting antibiotics"},{"id":"c","text":"Administer broad-spectrum antibiotics"},{"id":"d","text":"Begin a 30 mL/kg isotonic crystalloid bolus for hypotension"},{"id":"e","text":"Hold all fluids until blood pressure normalizes on its own"},{"id":"f","text":"Delay antibiotics until culture results return"}]',
 '["a","b","c","d"]',
 'The Surviving Sepsis Hour-1 bundle requires measuring lactate, drawing blood cultures before antibiotics, giving broad-spectrum antibiotics, and starting 30 mL/kg crystalloid for hypotension or lactate >=4. Holding fluids or delaying antibiotics increases mortality.',
 'Sepsis is a dysregulated host response to infection causing tissue hypoperfusion; this client meets criteria with fever, tachycardia, tachypnea, hypotension, and new confusion (a sign of end-organ hypoperfusion). The Surviving Sepsis Campaign Hour-1 bundle is time-critical because each hour of delayed antibiotics raises mortality ~4-7%. The four bundle elements: (a) measure lactate — a marker of anaerobic metabolism and the best early perfusion gauge, repeat if >2; (b) draw blood cultures BEFORE antibiotics so the pathogen is not masked; (c) give broad-spectrum antibiotics within the hour; (d) start 30 mL/kg isotonic crystalloid for hypotension or lactate >=4 to restore preload. The decisive reasoning: cultures-before-antibiotics is the one ordering rule that must not flip — but antibiotics are never delayed waiting on results. Pearl: in sepsis, lactate is your speedometer and the Hour-1 clock starts at recognition, not at ICU transfer.',
 '{"e":"Withholding fluids in a hypotensive septic client worsens hypoperfusion and accelerates organ failure — the bundle mandates 30 mL/kg crystalloid.","f":"Antibiotics are never delayed for culture results; cultures are drawn first only so they are not masked, then antibiotics start immediately."}',
 '[{"title":"Surviving Sepsis Campaign Guidelines 2021","citation":"Hour-1 bundle: lactate, cultures before antibiotics, broad-spectrum antibiotics, 30 mL/kg crystalloid.","href":"https://www.sccm.org/SurvivingSepsisCampaign/Guidelines"},{"title":"NCSBN NCLEX-RN Test Plan — Physiological Adaptation","citation":"Hemodynamics and sepsis management."}]',
 '["sepsis","perfusion","prioritization","NGN"]',
 'published', 'final-curated-live', unixepoch(), unixepoch());

-- 2. SATA — Increased intracranial pressure nursing interventions (Neuro / Physiological Adaptation)
INSERT OR REPLACE INTO questions (id, exam, type, category, subcategory, difficulty, stem, options, answer, rationale, deep_rationale, distractor_rationales, references_json, tags, publish_state, review_status, deep_rationale_authored_at, created_at)
VALUES (
 'gen-ngn-0002-icp-interventions', 'nclex', 'sata', 'increased_icp_management', 'Increased Intracranial Pressure', 4,
 'A client with a traumatic brain injury has an intracranial pressure (ICP) of 24 mm Hg. Which nursing interventions are appropriate to help lower the ICP? Select all that apply.',
 '[{"id":"a","text":"Elevate the head of the bed to 30 degrees with the head midline"},{"id":"b","text":"Keep the neck in a neutral position, avoiding flexion or rotation"},{"id":"c","text":"Cluster nursing care into one prolonged session"},{"id":"d","text":"Maintain a calm, quiet environment and minimize stimulation"},{"id":"e","text":"Suction the airway frequently and for prolonged periods"},{"id":"f","text":"Ensure normothermia and treat fever promptly"}]',
 '["a","b","d","f"]',
 'A normal ICP is 5-15 mm Hg; 24 is elevated. HOB 30 degrees with the head midline promotes venous drainage, neutral neck position prevents jugular compression, a quiet environment limits ICP spikes, and normothermia lowers cerebral metabolic demand. Clustering care and prolonged suctioning both raise ICP.',
 'ICP rises when any of the three intracranial volumes — brain, blood, or CSF — increases in the fixed skull (Monro-Kellie doctrine); sustained ICP >20-22 mm Hg threatens cerebral perfusion (CPP = MAP - ICP) and risks herniation. Each correct intervention targets a mechanism: HOB 30 degrees with a MIDLINE head uses gravity to improve jugular venous outflow without dropping cerebral perfusion (too high lowers CPP, too flat impairs drainage); a neutral neck prevents jugular compression that traps venous blood; a quiet, low-stimulation environment prevents the transient ICP surges that noxious stimuli trigger; and normothermia matters because every 1°C of fever raises cerebral metabolic rate ~7%, increasing blood flow and ICP. The two traps: clustering care into one long session stacks stimulation-induced spikes (space activities and allow recovery between), and prolonged/frequent suctioning causes dangerous transient ICP elevation (limit to <10 seconds, hyperoxygenate first). Pearl: midline head + 30 degrees + calm + cool — and never let a single activity stack ICP triggers.',
 '{"c":"Clustering care into one prolonged session stacks stimulation-induced ICP spikes; activities should be spaced with recovery time between them.","e":"Frequent prolonged suctioning causes dangerous transient ICP elevation — limit passes to under 10 seconds and hyperoxygenate first."}',
 '[{"title":"Brain Trauma Foundation Guidelines (4th ed.)","citation":"ICP and cerebral perfusion pressure management.","href":"https://braintrauma.org/guidelines"},{"title":"AACN Core Curriculum for Critical Care Nursing","citation":"Neurologic monitoring and ICP nursing interventions."}]',
 '["neuro","ICP","TBI","NGN"]',
 'published', 'final-curated-live', unixepoch(), unixepoch());

-- 3. SATA — DKA initial management priorities (Endocrine / Pharmacological)
INSERT OR REPLACE INTO questions (id, exam, type, category, subcategory, difficulty, stem, options, answer, rationale, deep_rationale, distractor_rationales, references_json, tags, publish_state, review_status, deep_rationale_authored_at, created_at)
VALUES (
 'gen-ngn-0003-dka-priorities', 'nclex', 'sata', 'dka_initial_management', 'Diabetic Ketoacidosis', 4,
 'A client arrives with diabetic ketoacidosis: blood glucose 612 mg/dL, pH 7.18, potassium 3.2 mEq/L, and Kussmaul respirations. Which actions should the nurse prioritize in the initial management? Select all that apply.',
 '[{"id":"a","text":"Begin a rapid isotonic (0.9% saline) IV fluid bolus"},{"id":"b","text":"Replace potassium before or alongside the insulin infusion"},{"id":"c","text":"Start a regular insulin infusion per protocol"},{"id":"d","text":"Administer IV insulin immediately as the very first action regardless of potassium"},{"id":"e","text":"Monitor potassium closely as insulin drives it intracellularly"},{"id":"f","text":"Give a large IV sodium bicarbonate push to correct the pH quickly"}]',
 '["a","b","c","e"]',
 'DKA management is fluids first, correct/monitor potassium, then insulin. This client''s potassium is already low (3.2); insulin would drive it lower and risk fatal arrhythmia, so potassium must be replaced before or with insulin. Bicarbonate is reserved for pH <6.9. Immediate insulin without addressing potassium is unsafe.',
 'DKA is profound insulin deficiency causing hyperglycemia, osmotic diuresis (6-10 L deficit), and ketoacidosis. The management sequence is mechanistic. First, isotonic saline restores the massive volume deficit and improves perfusion — fluids alone drop glucose by dilution and restored renal clearance. The potassium trap is the highest-yield concept: total-body potassium is always depleted in DKA, but the serum value can look normal or high because acidosis shifts K+ out of cells. THIS client is already frankly hypokalemic at 3.2 — starting insulin now would drive K+ intracellularly and precipitate lethal ventricular arrhythmia, so potassium must be repleted before or concurrently with insulin (most protocols hold insulin until K+ >3.3). Regular insulin infusion then closes the anion gap and clears ketones; add dextrose once glucose reaches ~200 to keep insulin running while ketones resolve. Bicarbonate is avoided unless pH <6.9 — it risks paradoxical CNS acidosis and hypokalemia. Pearl: in DKA, fluids before insulin, and never push insulin until you know the potassium.',
 '{"d":"Giving insulin first regardless of potassium is dangerous — with K+ at 3.2, insulin would drive it lower and risk fatal arrhythmia. Potassium must be addressed first.","f":"Sodium bicarbonate is reserved for severe acidosis (pH <6.9); routine use causes paradoxical CNS acidosis, hypokalemia, and is not indicated at pH 7.18."}',
 '[{"title":"ADA Standards of Care — Hyperglycemic Crises","citation":"DKA fluid, potassium, and insulin sequencing.","href":"https://diabetesjournals.org/care"},{"title":"NCSBN NCLEX-RN Test Plan — Pharmacological and Parenteral Therapies","citation":"Insulin administration and electrolyte safety."}]',
 '["endocrine","DKA","potassium","insulin","NGN"]',
 'published', 'final-curated-live', unixepoch(), unixepoch());

-- 4. MATRIX — Acute ischemic stroke: tPA eligibility (Neuro / Pharmacological)
INSERT OR REPLACE INTO questions (id, exam, type, category, subcategory, difficulty, stem, options, answer, rationale, deep_rationale, distractor_rationales, references_json, matrix_columns, matrix_rows, tags, publish_state, review_status, deep_rationale_authored_at, created_at)
VALUES (
 'gen-ngn-0004-tpa-eligibility', 'nclex', 'matrix', 'stroke_tpa_eligibility', 'Acute Ischemic Stroke — Thrombolytic Eligibility', 4,
 'A client presents with acute ischemic stroke symptoms that began 2 hours ago. For each finding, click to specify whether it SUPPORTS or is a CONTRAINDICATION to IV alteplase (tPA) administration.',
 '[{"id":"a","text":"Supports tPA"},{"id":"b","text":"Contraindication to tPA"}]',
 '{"Symptom onset 2 hours ago, within the 4.5-hour window":"Supports tPA","Blood pressure 198/118 mm Hg that does not lower below 185/110":"Contraindication to tPA","CT scan shows no hemorrhage":"Supports tPA","Active internal bleeding or recent major surgery within 14 days":"Contraindication to tPA","Platelet count 90,000/microL (below 100,000)":"Contraindication to tPA","Measurable neurologic deficit on the NIH Stroke Scale":"Supports tPA"}',
 'tPA dissolves the clot in ischemic stroke but carries a hemorrhage risk, so eligibility hinges on timing and bleeding safety. Onset within 4.5 hours, a non-hemorrhagic CT, and a measurable deficit support treatment. Uncontrolled BP >185/110, active bleeding/recent surgery, and platelets <100,000 are contraindications.',
 'Alteplase (tPA) is a thrombolytic that converts plasminogen to plasmin to lyse the occluding clot in acute ischemic stroke; its benefit is exquisitely time-dependent (treat within 4.5 hours of last-known-well) and its danger is symptomatic intracranial hemorrhage. Each row maps to an eligibility rule. SUPPORTS: onset 2 hours ago sits inside the 4.5-hour window; a CT showing no hemorrhage confirms the stroke is ischemic (you must exclude bleed before lysing); a measurable NIHSS deficit establishes a treatable stroke. CONTRAINDICATIONS: blood pressure that will not come below 185/110 sharply raises hemorrhage risk and must be controlled with labetalol/nicardipine first; active internal bleeding or major surgery within 14 days creates unacceptable systemic bleeding risk; and platelets below 100,000 impair hemostasis. Pearl: before tPA, confirm the clock (<=4.5h), the CT (no blood), the pressure (<185/110), and the bleeding history — any single hard contraindication cancels the drug.',
 NULL,
 '[{"title":"AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke 2019","citation":"IV alteplase eligibility and exclusion criteria.","href":"https://www.ahajournals.org/doi/10.1161/STR.0000000000000211"}]',
 '["Supports tPA","Contraindication to tPA"]',
 '[{"label":"Symptom onset 2 hours ago, within the 4.5-hour window","answer":"Supports tPA"},{"label":"Blood pressure 198/118 mm Hg that does not lower below 185/110","answer":"Contraindication to tPA"},{"label":"CT scan shows no hemorrhage","answer":"Supports tPA"},{"label":"Active internal bleeding or recent major surgery within 14 days","answer":"Contraindication to tPA"},{"label":"Platelet count 90,000/microL (below 100,000)","answer":"Contraindication to tPA"},{"label":"Measurable neurologic deficit on the NIH Stroke Scale","answer":"Supports tPA"}]',
 '["neuro","stroke","tPA","thrombolytic","NGN","matrix"]',
 'published', 'final-curated-live', unixepoch(), unixepoch());

-- 5. MATRIX — Magnesium sulfate in preeclampsia: expected vs toxicity (OB / Pharmacological)
INSERT OR REPLACE INTO questions (id, exam, type, category, subcategory, difficulty, stem, options, answer, rationale, deep_rationale, distractor_rationales, references_json, matrix_columns, matrix_rows, tags, publish_state, review_status, deep_rationale_authored_at, created_at)
VALUES (
 'gen-ngn-0005-mag-toxicity', 'nclex', 'matrix', 'magnesium_sulfate_monitoring', 'Magnesium Sulfate — Preeclampsia', 4,
 'A client with severe preeclampsia is receiving an IV magnesium sulfate infusion. For each finding, click to specify whether it is an EXPECTED therapeutic finding or a sign of MAGNESIUM TOXICITY requiring intervention.',
 '[{"id":"a","text":"Expected therapeutic finding"},{"id":"b","text":"Magnesium toxicity"}]',
 '{"Deep tendon reflexes present and 2+ (normal)":"Expected therapeutic finding","Respiratory rate 10 breaths/min":"Magnesium toxicity","Absent deep tendon reflexes":"Magnesium toxicity","Blood pressure trending down toward normal":"Expected therapeutic finding","Urine output 15 mL/hr":"Magnesium toxicity","Mild drowsiness and flushing":"Expected therapeutic finding"}',
 'Magnesium sulfate prevents seizures in preeclampsia but is a CNS/neuromuscular depressant with a narrow window. Present 2+ reflexes, a downtrending BP, and mild drowsiness/flushing are expected. Absent reflexes, respiratory rate <12, and oliguria (<30 mL/hr) signal toxicity — stop the infusion and give calcium gluconate.',
 'Magnesium sulfate raises the seizure threshold in preeclampsia/eclampsia by acting as a CNS depressant and smooth-muscle relaxant; the therapeutic range is roughly 4-7 mEq/L and toxicity climbs predictably as the level rises. Each row reflects where the client sits on that curve. EXPECTED: intact 2+ deep tendon reflexes confirm the level is therapeutic but not toxic (reflexes are the bedside early-warning system); a blood pressure drifting toward normal is the desired effect; mild drowsiness and flushing are common benign effects of CNS depression and vasodilation. TOXICITY: loss of deep tendon reflexes is the FIRST reliable warning (around 8-10 mEq/L) and the signal to stop the drip; respiratory rate below 12 reflects respiratory-center depression (~10-12 mEq/L) and precedes cardiac arrest; and urine output below 30 mL/hr is critical because magnesium is renally cleared — oliguria causes rapid accumulation. The antidote is IV calcium gluconate. Pearl: monitor reflexes, respirations (keep >12), and urine output (>30 mL/hr) every hour — absent reflexes means stop the magnesium and reach for calcium gluconate.',
 NULL,
 '[{"title":"ACOG Practice Bulletin — Gestational Hypertension and Preeclampsia","citation":"Magnesium sulfate dosing, monitoring, and toxicity management.","href":"https://www.acog.org"},{"title":"AWHONN Perinatal Nursing Standards","citation":"Magnesium sulfate safety monitoring."}]',
 '["Expected therapeutic finding","Magnesium toxicity"]',
 '[{"label":"Deep tendon reflexes present and 2+ (normal)","answer":"Expected therapeutic finding"},{"label":"Respiratory rate 10 breaths/min","answer":"Magnesium toxicity"},{"label":"Absent deep tendon reflexes","answer":"Magnesium toxicity"},{"label":"Blood pressure trending down toward normal","answer":"Expected therapeutic finding"},{"label":"Urine output 15 mL/hr","answer":"Magnesium toxicity"},{"label":"Mild drowsiness and flushing","answer":"Expected therapeutic finding"}]',
 '["OB","preeclampsia","magnesium","NGN","matrix"]',
 'published', 'final-curated-live', unixepoch(), unixepoch());
